var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return $jscomp.createTemplateTagFirstArgWithRaw(a,a)};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_ES6=!1;$jscomp.ASSUME_ES2020=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.INSTRUMENT_ASYNC_CONTEXT=!0;$jscomp.defineProperty=$jscomp.ASSUME_ES5||typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.ASSUME_ES2020?globalThis:$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE=typeof Symbol==="function"&&typeof Symbol("x")==="symbol";$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;
$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var JSCompiler_inline_result$jscomp$4,classes$jscomp$inline_6="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");$jscomp.global.BigInt64Array&&(classes$jscomp$inline_6.push("BigInt64"),classes$jscomp$inline_6.push("BigUint64"));JSCompiler_inline_result$jscomp$4=classes$jscomp$inline_6;$jscomp.TYPED_ARRAY_CLASSES=JSCompiler_inline_result$jscomp$4;
$jscomp.polyfillTypedArrayMethod=function(a,b,c,d){if(b)for(var e=0;e<$jscomp.TYPED_ARRAY_CLASSES.length;e++){var h=$jscomp.TYPED_ARRAY_CLASSES[e]+"Array.prototype."+a;$jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(h,b,c,d):$jscomp.polyfillUnisolated(h,b,c,d)}};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b){var c=$jscomp.global;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c){var d=a.split("."),e=d.length===1;a=d[0];a=!e&&a in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<d.length-1;h++){var m=d[h];if(!(m in a))return;a=a[m]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&c==="es6"?a[d]:null;b=b(c);b!=null&&(e?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]===void 0&&(e=Math.random()*1E9>>>0,$jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+e+"$"+d),e=$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(a,e,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.ASSUME_ES6||$jscomp.TRUST_ES6_POLYFILLS&&typeof Object.setPrototypeOf=="function"?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.getNextAddressJsc=function(){return this.nextAddress};$jscomp.generator.Context.prototype.getYieldResultJsc=function(){return this.yieldResult};
$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype["return"]=$jscomp.generator.Context.prototype.return;$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks;
$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yield=$jscomp.generator.Context.prototype.yield;$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};$jscomp.generator.Context.prototype.yieldAll=$jscomp.generator.Context.prototype.yieldAll;
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpTo=$jscomp.generator.Context.prototype.jumpTo;$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.jumpToEnd=$jscomp.generator.Context.prototype.jumpToEnd;$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;b!=void 0&&(this.finallyAddress_=b)};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=$jscomp.generator.Context.prototype.setCatchFinallyBlocks;$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.setFinallyBlock=$jscomp.generator.Context.prototype.setFinallyBlock;$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};$jscomp.generator.Context.prototype.leaveTryBlock=$jscomp.generator.Context.prototype.leaveTryBlock;
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterCatchBlock=$jscomp.generator.Context.prototype.enterCatchBlock;$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.enterFinallyBlock=$jscomp.generator.Context.prototype.enterFinallyBlock;$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();b.jumpTo!=void 0&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};
$jscomp.generator.Context.prototype.leaveFinallyBlock=$jscomp.generator.Context.prototype.leaveFinallyBlock;$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};$jscomp.generator.Context.prototype.forIn=$jscomp.generator.Context.prototype.forIn;$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};
$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;this.properties_.length>0;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Context.PropertyIterator.prototype.getNext=$jscomp.generator.Context.PropertyIterator.prototype.getNext;$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return b="return"in b?b["return"]:function(c){return{value:c,done:!0}},this.yieldAllStep_(b,a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(h){return this.context_.yieldAllIterator_=null,this.context_.throw_(h),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function h(m){m.done?d(m.value):Promise.resolve(m.value).then(b,c).then(h,e)}h(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.polyfill("globalThis",function(a){return a||$jscomp.global},"es_2020","es3");$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(h,m){this.$jscomp$symbol$id_=h;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:m})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};a=Math.random()*1E9>>>0;var c="jscomp_symbol_"+a+"_",d=0,e=function(h){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(h||"")+"_"+d++,h)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});return a},"es6","es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(k){return k instanceof h?k:new h(function(f){f(k)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&typeof $jscomp.global.PromiseRejectionEvent==="undefined")||!$jscomp.global.Promise||$jscomp.global.Promise.toString().indexOf("[native code]")===-1))return a;b.prototype.asyncExecute=function(k){if(this.batch_==null){this.batch_=[];var f=this;this.asyncExecuteFunction(function(){f.executeBatch_()})}this.batch_.push(k)};
var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(k){d(k,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var k=this.batch_;this.batch_=[];for(var f=0;f<k.length;++f){var g=k[f];k[f]=null;try{g()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(k){this.asyncExecuteFunction(function(){throw k;})};var e={PENDING:0,FULFILLED:1,REJECTED:2},h=function(k){this.state_=e.PENDING;this.result_=void 0;this.onSettledCallbacks_=
[];this.isRejectionHandled_=!1;var f=this.createResolveAndReject_();try{k(f.resolve,f.reject)}catch(g){f.reject(g)}};h.prototype.createResolveAndReject_=function(){function k(l){return function(n){g||(g=!0,l.call(f,n))}}var f=this,g=!1;return{resolve:k(this.resolveTo_),reject:k(this.reject_)}};h.prototype.resolveTo_=function(k){if(k===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(k instanceof h)this.settleSameAsPromise_(k);else{a:switch(typeof k){case "object":var f=
k!=null;break a;case "function":f=!0;break a;default:f=!1}f?this.resolveToNonPromiseObj_(k):this.fulfill_(k)}};h.prototype.resolveToNonPromiseObj_=function(k){var f=void 0;try{f=k.then}catch(g){this.reject_(g);return}typeof f=="function"?this.settleSameAsThenable_(f,k):this.fulfill_(k)};h.prototype.reject_=function(k){this.settle_(e.REJECTED,k)};h.prototype.fulfill_=function(k){this.settle_(e.FULFILLED,k)};h.prototype.settle_=function(k,f){if(this.state_!=e.PENDING)throw Error("Cannot settle("+k+
", "+f+"): Promise already settled in state"+this.state_);this.state_=k;this.result_=f;this.state_===e.REJECTED&&this.scheduleUnhandledRejectionCheck_();this.executeOnSettledCallbacks_()};h.prototype.scheduleUnhandledRejectionCheck_=function(){var k=this;d(function(){if(k.notifyUnhandledRejection_()){var f=$jscomp.global.console;typeof f!=="undefined"&&f.error(k.result_)}},1)};h.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var k=$jscomp.global.CustomEvent,f=
$jscomp.global.Event,g=$jscomp.global.dispatchEvent;if(typeof g==="undefined")return!0;typeof k==="function"?k=new k("unhandledrejection",{cancelable:!0}):typeof f==="function"?k=new f("unhandledrejection",{cancelable:!0}):(k=$jscomp.global.document.createEvent("CustomEvent"),k.initCustomEvent("unhandledrejection",!1,!0,k));k.promise=this;k.reason=this.result_;return g(k)};h.prototype.executeOnSettledCallbacks_=function(){if(this.onSettledCallbacks_!=null){for(var k=0;k<this.onSettledCallbacks_.length;++k)m.asyncExecute(this.onSettledCallbacks_[k]);
this.onSettledCallbacks_=null}};var m=new b;h.prototype.settleSameAsPromise_=function(k){var f=this.createResolveAndReject_();k.callWhenSettled_(f.resolve,f.reject)};h.prototype.settleSameAsThenable_=function(k,f){var g=this.createResolveAndReject_();try{k.call(f,g.resolve,g.reject)}catch(l){g.reject(l)}};h.prototype.then=function(k,f){function g(q,r){return typeof q=="function"?function(t){try{l(q(t))}catch(u){n(u)}}:r}var l,n,p=new h(function(q,r){l=q;n=r});this.callWhenSettled_(g(k,l),g(f,n));
return p};h.prototype.catch=function(k){return this.then(void 0,k)};h.prototype.callWhenSettled_=function(k,f){function g(){switch(l.state_){case e.FULFILLED:k(l.result_);break;case e.REJECTED:f(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;this.onSettledCallbacks_==null?m.asyncExecute(g):this.onSettledCallbacks_.push(g);this.isRejectionHandled_=!0};h.resolve=c;h.reject=function(k){return new h(function(f,g){g(k)})};h.race=function(k){return new h(function(f,g){for(var l=
$jscomp.makeIterator(k),n=l.next();!n.done;n=l.next())c(n.value).callWhenSettled_(f,g)})};h.all=function(k){var f=$jscomp.makeIterator(k),g=f.next();return g.done?c([]):new h(function(l,n){function p(t){return function(u){q[t]=u;r--;r==0&&l(q)}}var q=[],r=0;do q.push(void 0),r++,c(g.value).callWhenSettled_(p(q.length-1),n),g=f.next();while(!g.done)})};return h},"es6","es3");$jscomp.polyfill("Object.setPrototypeOf",function(a){return a||$jscomp.setPrototypeOf},"es6","es5");
$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.toObject=function(a){if(a==null)throw new TypeError("No nullish arg");return Object(a)};$jscomp.assign=$jscomp.ASSUME_ES6||$jscomp.TRUST_ES6_POLYFILLS&&typeof Object.assign=="function"?Object.assign:function(a,b){a=$jscomp.toObject(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)$jscomp.owns(d,e)&&(a[e]=d[e])}return a};
$jscomp.objectCreate=$jscomp.ASSUME_ES5||typeof Object.create=="function"?Object.create:function(a){var b=function(){};b.prototype=a;return new b};$jscomp.inherits=function(a,b){a.prototype=$jscomp.objectCreate(b.prototype);a.prototype.constructor=a;if($jscomp.ASSUME_ES6||$jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(a,b)}else for(c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.superClass_=b.prototype};
$jscomp.getConstructImplementation=function(){function a(){function e(){}function h(){}new e;Reflect.construct(e,[],h);return new e instanceof e}function b(e,h,m){m===void 0&&(m=e);m=m.prototype||Object.prototype;m=$jscomp.objectCreate(m);var k=Function.prototype.apply;return(e=k.call(e,m,h))||m}if($jscomp.TRUST_ES6_POLYFILLS&&typeof Reflect!="undefined"&&Reflect.construct){if(a())return Reflect.construct;var c=Reflect.construct,d=function(e,h,m){e=c(e,h);m&&Reflect.setPrototypeOf(e,m.prototype);
return e};return d}return b};$jscomp.construct={valueOf:$jscomp.getConstructImplementation}.valueOf();$jscomp.polyfill("Reflect",function(a){return a?a:{}},"es6","es3");$jscomp.polyfill("Reflect.construct",function(){return $jscomp.construct},"es6","es3");
$jscomp.polyfill("Array.from",function(a){return a?a:a=function(b,c,d){c=c!=null?c:function(k){return k};var e=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h=="function"){b=h.call(b);for(var m=0;!(h=b.next()).done;)e.push(c.call(d,h.value,m++))}else for(h=b.length,m=0;m<h;m++)e.push(c.call(d,b[m],m));return e}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:a=function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:a=function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:a=function(b,c){var d=$jscomp.checkStringArgs(this,b,"includes");return d.indexOf(b,c||0)!==-1}},"es6","es3");
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var h=a[e];if(b.call(c,h,e,a))return{i:e,v:h}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:a=function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(c,d,e){return c==a&&d=="q"&&e==b}}));return b.q===!0}catch(c){return!1}};
$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),l=Object.seal({}),n=new a([[g,2],[l,3]]);if(n.get(g)!=2||n.get(l)!=3)return!1;n.delete(g);n.set(l,4);return!n.has(g)&&n.get(l)==4}catch(p){return!1}}function c(){}function d(g){var l=typeof g;return l==="object"&&g!==null||l==="function"}function e(g){if(!$jscomp.owns(g,m)){var l=new c;$jscomp.defineProperty(g,m,{value:l})}}function h(g){if(!$jscomp.ISOLATE_POLYFILLS){var l=Object[g];l&&(Object[g]=
function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return l(n)})}}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var m="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var k=0,f=function(g){this.id_=(k+=Math.random()+1).toString();if(g){g=$jscomp.makeIterator(g);for(var l;!(l=g.next()).done;)l=l.value,this.set(l[0],l[1])}};f.prototype.set=function(g,l){if(!d(g))throw Error("Invalid WeakMap key");
e(g);if(!$jscomp.owns(g,m))throw Error("WeakMap key fail: "+g);g[m][this.id_]=l;return this};f.prototype.get=function(g){return d(g)&&$jscomp.owns(g,m)?g[m][this.id_]:void 0};f.prototype.has=function(g){return d(g)&&$jscomp.owns(g,m)&&$jscomp.owns(g[m],this.id_)};f.prototype.delete=function(g){return d(g)&&$jscomp.owns(g,m)&&$jscomp.owns(g[m],this.id_)?delete g[m][this.id_]:!1};return f},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var f=Object.seal({x:4}),g=new a($jscomp.makeIterator([[f,"s"]]));if(g.get(f)!="s"||g.size!=1||g.get({x:4})||g.set({x:4},"t")!=g||g.size!=2)return!1;var l=g.entries(),n=l.next();if(n.done||n.value[0]!=f||n.value[1]!="s")return!1;n=l.next();return n.done||n.value[0].x!=4||n.value[1]!="t"||!l.next().done?!1:!0}catch(p){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var c=new WeakMap,d=function(f){this[0]={};this[1]=m();this.size=0;if(f){f=$jscomp.makeIterator(f);for(var g;!(g=f.next()).done;)g=g.value,this.set(g[0],g[1])}};d.prototype.set=function(f,g){f=f===0?0:f;var l=e(this,f);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=g:(l.entry={next:this[1],previous:this[1].previous,head:this[1],key:f,value:g},l.list.push(l.entry),this[1].previous.next=
l.entry,this[1].previous=l.entry,this.size++);return this};d.prototype.delete=function(f){f=e(this,f);return f.entry&&f.list?(f.list.splice(f.index,1),f.list.length||delete this[0][f.id],f.entry.previous.next=f.entry.next,f.entry.next.previous=f.entry.previous,f.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this[0]={};this[1]=this[1].previous=m();this.size=0};d.prototype.has=function(f){return!!e(this,f).entry};d.prototype.get=function(f){return(f=e(this,f).entry)&&f.value};d.prototype.entries=
function(){return h(this,function(f){return[f.key,f.value]})};d.prototype.keys=function(){return h(this,function(f){return f.key})};d.prototype.values=function(){return h(this,function(f){return f.value})};d.prototype.forEach=function(f,g){for(var l=this.entries(),n;!(n=l.next()).done;)n=n.value,f.call(g,n[1],n[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var e=function(f,g){var l;var n=(l=g)&&typeof l;n=="object"||n=="function"?c.has(l)?l=c.get(l):(n=""+ ++k,c.set(l,n),l=n):l="p_"+
l;if((n=f[0][l])&&$jscomp.owns(f[0],l))for(f=0;f<n.length;f++){var p=n[f];if(g!==g&&p.key!==p.key||g===p.key)return{id:l,list:n,index:f,entry:p}}return{id:l,list:n,index:-1,entry:void 0}},h=function(f,g){var l=f[1];return $jscomp.iteratorPrototype(function(){if(l){for(;l.head!=f[1];)l=l.previous;for(;l.next!=l.head;)return l=l.next,{done:!1,value:g(l)};l=null}return{done:!0,value:void 0}})},m=function(){var f={};return f.previous=f.next=f.head=f},k=0;return d},"es6","es3");
$jscomp.iteratorFromArray=function(a,b){if($jscomp.ASSUME_ES6)return a[Symbol.iterator]();a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:a=function(){return $jscomp.iteratorFromArray(this,function(b,c){return[b,c]})}},"es6","es3");/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var goog=goog||{};goog.global=this||self;goog.exportPath_=function(a,b,c,d){a=a.split(".");d=d||goog.global;for(var e;a.length&&(e=a.shift());)if(a.length||b===void 0)d=d[e]&&d[e]!==Object.prototype[e]?d[e]:d[e]={};else if(!c&&goog.isObject(b)&&goog.isObject(d[e]))for(var h in b)b.hasOwnProperty(h)&&(d[e][h]=b[h]);else d[e]=b};goog.CLOSURE_DEFINES=typeof CLOSURE_DEFINES!=="undefined"?CLOSURE_DEFINES:goog.global.CLOSURE_DEFINES;
goog.CLOSURE_UNCOMPILED_DEFINES=typeof CLOSURE_UNCOMPILED_DEFINES!=="undefined"?CLOSURE_UNCOMPILED_DEFINES:goog.global.CLOSURE_UNCOMPILED_DEFINES;goog.define=function(a,b){return a=b};goog.FEATURESET_YEAR=2012;goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;goog.DISALLOW_TEST_ONLY_CODE=!goog.DEBUG;goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING=!1;goog.readFlagInternalDoNotUseOrElse=function(a,b){var c=goog.getObjectByName(goog.FLAGS_OBJECT_);a=c&&c[a];return a!=null?a:b};goog.FLAGS_OBJECT_="CLOSURE_FLAGS";
goog.FLAGS_STAGING_DEFAULT=!0;goog.CLOSURE_TOGGLE_ORDINALS=typeof CLOSURE_TOGGLE_ORDINALS==="object"?CLOSURE_TOGGLE_ORDINALS:goog.global.CLOSURE_TOGGLE_ORDINALS;goog.readToggleInternalDoNotCallDirectly=function(a){var b=goog.CLOSURE_TOGGLE_ORDINALS;a=b&&b[a];return typeof a!=="number"?!!a:!!(goog.TOGGLES_[Math.floor(a/30)]&1<<a%30)};goog.TOGGLE_VAR_="_F_toggles";goog.TOGGLES_=goog.global[goog.TOGGLE_VAR_]||[];goog.GENDERED_MESSAGES_ENABLED=!0;
goog.GrammaticalGender_={OTHER:0,MASCULINE:1,FEMININE:2,NEUTER:3};goog.GRAMMATICAL_GENDER_MAP_={FEMININE:goog.GrammaticalGender_.FEMININE,MASCULINE:goog.GrammaticalGender_.MASCULINE,NEUTER:goog.GrammaticalGender_.NEUTER};goog.viewerGrammaticalGender_=goog.GRAMMATICAL_GENDER_MAP_[goog.GENDERED_MESSAGES_ENABLED&&goog.global._F_VIEWER_GRAMMATICAL_GENDER]||goog.GrammaticalGender_.OTHER;goog.msgKind={};goog.msgKind.MASCULINE=goog.viewerGrammaticalGender_===goog.GrammaticalGender_.MASCULINE;
goog.msgKind.FEMININE=goog.viewerGrammaticalGender_===goog.GrammaticalGender_.FEMININE;goog.msgKind.NEUTER=goog.viewerGrammaticalGender_===goog.GrammaticalGender_.NEUTER;goog.LEGACY_NAMESPACE_OBJECT_=goog.global;goog.provide=function(a){if(goog.isInModuleLoader_())throw Error("goog.provide cannot be used within a module.");goog.constructNamespace_(a)};goog.constructNamespace_=function(a,b,c){goog.exportPath_(a,b,c,goog.LEGACY_NAMESPACE_OBJECT_)};goog.NONCE_PATTERN_=/^[\w+/_-]+[=]{0,2}$/;
goog.getScriptNonce_=function(a){a=(a||goog.global).document;return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&goog.NONCE_PATTERN_.test(a)?a:""};goog.VALID_MODULE_RE_=/^[a-zA-Z_$][a-zA-Z0-9._$]*$/;goog.module=function(){};goog.module.get=function(){return null};goog.module.getInternal_=function(){return null};goog.requireDynamic=function(){return null};goog.importHandler_=null;goog.uncompiledChunkIdHandler_=null;
goog.setImportHandlerInternalDoNotCallOrElse=function(a){goog.importHandler_=a};goog.setUncompiledChunkIdHandlerInternalDoNotCallOrElse=function(a){goog.uncompiledChunkIdHandler_=a};goog.maybeRequireFrameworkInternalOnlyDoNotCallOrElse=function(){};goog.ModuleType={ES6:"es6",GOOG:"goog"};goog.moduleLoaderState_=null;goog.isInModuleLoader_=function(){return goog.isInGoogModuleLoader_()||goog.isInEs6ModuleLoader_()};
goog.isInGoogModuleLoader_=function(){return!!goog.moduleLoaderState_&&goog.moduleLoaderState_.type==goog.ModuleType.GOOG};goog.isInEs6ModuleLoader_=function(){var a=!!goog.moduleLoaderState_&&goog.moduleLoaderState_.type==goog.ModuleType.ES6;return a?!0:(a=goog.LEGACY_NAMESPACE_OBJECT_.$jscomp)?typeof a.getCurrentModulePath!="function"?!1:!!a.getCurrentModulePath():!1};goog.module.declareLegacyNamespace=function(){goog.moduleLoaderState_.declareLegacyNamespace=!0};
goog.module.preventModuleExportSealing=function(){goog.moduleLoaderState_.preventModuleExportSealing=!0};goog.declareModuleId=function(a){if(goog.moduleLoaderState_)goog.moduleLoaderState_.moduleName=a;else{var b=goog.LEGACY_NAMESPACE_OBJECT_.$jscomp;if(!b||typeof b.getCurrentModulePath!="function")throw Error('Module with namespace "'+a+'" has been loaded incorrectly.');b=b.require(b.getCurrentModulePath());goog.loadedModules_[a]={exports:b,type:goog.ModuleType.ES6,moduleId:a}}};
goog.setTestOnly=function(a){if(goog.DISALLOW_TEST_ONLY_CODE)throw a=a||"",Error("Importing test-only code into non-debug environment"+(a?": "+a:"."));};goog.forwardDeclare=function(){};goog.getObjectByName=function(a,b){a=a.split(".");b=b||goog.global;for(var c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b};goog.addDependency=function(){};goog.ENABLE_DEBUG_LOADER=!1;goog.logToConsole_=function(a){goog.global.console&&goog.global.console.error(a)};goog.require=function(){};
goog.requireType=function(){return{}};goog.basePath="";goog.abstractMethod=function(){throw Error("unimplemented abstract method");};goog.addSingletonGetter=function(a){a.instance_=void 0;a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];goog.LOAD_MODULE_USING_EVAL=!0;goog.SEAL_MODULE_EXPORTS=goog.DEBUG;goog.loadedModules_={};
goog.DEPENDENCIES_ENABLED=!1;goog.ASSUME_ES_MODULES_TRANSPILED=!1;goog.TRUSTED_TYPES_POLICY_NAME="goog";
goog.loadModule=function(a){var b=goog.moduleLoaderState_;try{goog.moduleLoaderState_={moduleName:"",declareLegacyNamespace:!1,preventModuleExportSealing:!1,type:goog.ModuleType.GOOG};var c={},d=c;if(typeof a==="function")d=a.call(void 0,d);else if(typeof a==="string")d=goog.loadModuleFromSource_.call(void 0,d,a);else throw Error("Invalid module definition");var e=goog.moduleLoaderState_.moduleName;if(typeof e==="string"&&e){goog.moduleLoaderState_.declareLegacyNamespace?(a=c!==d,goog.constructNamespace_(e,
d,a)):goog.SEAL_MODULE_EXPORTS&&Object.seal&&typeof d=="object"&&d!=null&&!goog.moduleLoaderState_.preventModuleExportSealing&&Object.seal(d);var h={exports:d,type:goog.ModuleType.GOOG,moduleId:goog.moduleLoaderState_.moduleName};goog.loadedModules_[e]=h}else throw Error('Invalid module name "'+e+'"');}finally{goog.moduleLoaderState_=b}};goog.loadModuleFromSource_=function(a){eval(goog.CLOSURE_EVAL_PREFILTER_.createScript(arguments[1]));return a};
goog.normalizePath_=function(a){a=a.split("/");for(var b=0;b<a.length;)a[b]=="."?a.splice(b,1):b&&a[b]==".."&&a[b-1]&&a[b-1]!=".."?a.splice(--b,2):b++;return a.join("/")};goog.loadFileSync_=function(a){if(goog.global.CLOSURE_LOAD_FILE_SYNC)return goog.global.CLOSURE_LOAD_FILE_SYNC(a);try{var b=new goog.global.XMLHttpRequest;b.open("get",a,!1);b.send();return b.status==0||b.status==200?b.responseText:null}catch(c){return null}};
goog.typeOf=function(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"};goog.isArrayLike=function(a){var b=goog.typeOf(a);return b=="array"||b=="object"&&typeof a.length=="number"};goog.isDateLike=function(a){return goog.isObject(a)&&typeof a.getFullYear=="function"};goog.isObject=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"};
goog.getUid=function(a){return Object.prototype.hasOwnProperty.call(a,goog.UID_PROPERTY_)&&a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.hasUid=function(a){return!!a[goog.UID_PROPERTY_]};goog.removeUid=function(a){a!==null&&"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};goog.UID_PROPERTY_="closure_uid_"+(Math.random()*1E9>>>0);goog.uidCounter_=0;
goog.cloneObject=function(a){var b=goog.typeOf(a);if(b=="object"||b=="array"){if(typeof a.clone==="function")return a.clone();if(typeof Map!=="undefined"&&a instanceof Map)return new Map(a);if(typeof Set!=="undefined"&&a instanceof Set)return new Set(a);b=b=="array"?[]:{};for(var c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};
goog.bind=function(a,b,c){goog.bind=goog.TRUSTED_SITE&&goog.FEATURESET_YEAR>2012||Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?goog.bindNative_:goog.bindJs_;return goog.bind.apply(null,arguments)};goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};goog.now=function(){return Date.now()};goog.globalEval=function(a){(0,eval)(a)};
goog.getCssName=function(a,b){if(String(a).charAt(0)==".")throw Error('className passed in goog.getCssName must not start with ".". You passed: '+a);var c=function(e){return goog.cssNameMapping_[e]||e},d=function(e){e=e.split("-");for(var h=[],m=0;m<e.length;m++)h.push(c(e[m]));return h.join("-")};d=goog.cssNameMapping_?goog.cssNameMappingStyle_=="BY_WHOLE"?c:d:function(e){return e};a=b?a+"-"+d(b):d(a);return goog.global.CLOSURE_CSS_NAME_MAP_FN?goog.global.CLOSURE_CSS_NAME_MAP_FN(a):a};
goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};goog.GetMsgOptions=function(){};goog.USE_GET_MSG_OVERRIDE=!1;goog.getMsg=function(a,b,c){c&&c.html&&(a=a.replace(/</g,"&lt;"));c&&c.unescapeHtmlEntities&&(a=a.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&apos;/g,"'").replace(/&quot;/g,'"').replace(/&amp;/g,"&"));b&&(a=a.replace(/\{\$([^}]+)}/g,function(d,e){return b!=null&&e in b?b[e]:d}));return a};goog.getMsgWithFallback=function(a){return a};
goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,!0,c)};goog.exportProperty=function(a,b,c){a[b]=c};goog.weakUsage=function(a){return a};goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,e,h){for(var m=Array(arguments.length-2),k=2;k<arguments.length;k++)m[k-2]=arguments[k];return b.prototype[e].apply(d,m)}};
goog.scope=function(a){if(goog.isInModuleLoader_())throw Error("goog.scope is not supported within a module.");a.call(goog.global)};goog.identity_=function(a){return a};goog.createTrustedTypesPolicy=function(a){var b=null,c=goog.global.trustedTypes;if(!c||!c.createPolicy)return b;try{b=c.createPolicy(a,{createHTML:goog.identity_,createScript:goog.identity_,createScriptURL:goog.identity_})}catch(d){goog.logToConsole_(d.message)}return b};goog.CodeLocation={DO_NOT_USE:"",DO_NOT_USE_ME_EITHER:"."};
goog.callerLocation=function(){return""};goog.callerLocationIdInternalDoNotCallOrElse=function(a){return a};var module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection={MicrosoftPageType:{STAY_SIGNED_IN:0,SIGN_IN:1,DOMAIN_CONFIRMATION:2,ERROR:3,UNKNOWN:4}};module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType[module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.STAY_SIGNED_IN]="STAY_SIGNED_IN";
module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType[module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.SIGN_IN]="SIGN_IN";module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType[module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.DOMAIN_CONFIRMATION]="DOMAIN_CONFIRMATION";
module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType[module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.ERROR]="ERROR";module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType[module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.UNKNOWN]="UNKNOWN";
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_DomainConfirmationElements(){}module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.DomainConfirmationElements=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_DomainConfirmationElements;
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_hasElementWhichMatchesText(a,b,c){return Array.from(a.querySelectorAll(b)).some(function(d){var e;return(e=d.textContent)==null?void 0:e.match(c)})}
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getErrorPageConfidence(a){var b=[];b.push(a.getElementById("ErrorDescription")||a.querySelector("#exceptionMessageContainer"));b.push(module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_hasElementWhichMatchesText(a,"div",RegExp("(W|w)e(\\'re| are) having troubles signing you in")));return b.filter(function(c){return c}).length/b.length}
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getSigninPageConfidence(a){var b=[];b.push(a.querySelector('form[action$="/login"]'));b.push(a.getElementById("tilesHolder")||a.querySelector('input[type="email"]')||a.querySelector('input[type="password"]'));b.push(module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_hasElementWhichMatchesText(a,"div",RegExp("^Sign in$"))||module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_hasElementWhichMatchesText(a,
"div",RegExp("^Enter password$"))||module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_hasElementWhichMatchesText(a,"div",RegExp("^Pick an account$"))||module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_hasElementWhichMatchesText(a,"div",RegExp("(W|w)e(\\'re| are) having trouble locating your account")));return b.filter(function(c){return c}).length/b.length}
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getStaySignedInPageConfidence(a){var b=[];b.push(a.querySelector('form[action="/kmsi"]'));b.push(a.getElementById("KmsiDescription"));b.push(module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_hasElementWhichMatchesText(a,"div",RegExp("^Stay signed in\\?$")));return b.filter(function(c){return c}).length/b.length}
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getDomainConfirmationPageConfidence(a){var b=[];b.push(a.querySelector('form[action="/appverify"]'));b.push(a.getElementById("appConfirmTitle"));b.push(module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_hasElementWhichMatchesText(a,"div",RegExp("^Do you trust")));return b.filter(function(c){return c}).length/b.length}
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_tryGetMicrosoftPageFromElements(a){a=[[module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.ERROR,module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getErrorPageConfidence(a)],[module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.SIGN_IN,module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getSigninPageConfidence(a)],
[module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.STAY_SIGNED_IN,module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getStaySignedInPageConfidence(a)],[module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.DOMAIN_CONFIRMATION,module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getDomainConfirmationPageConfidence(a)]];
a=a.filter(function(b){b=(0,$jscomp.makeIterator)(b);b.next();b=b.next().value;return b>0});return a.length!==1?module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.UNKNOWN:a[0][0]}
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getMicrosoftPageWithTimeout(a){var b,c,d,e,h,m,k;return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(f){if(f.nextAddress==1){b=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_tryGetMicrosoftPageFromElements(a);if(b!==module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.UNKNOWN)return f.return(b);e=
new Promise(function(g){c=setTimeout(function(){g(module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.UNKNOWN)},5E3)});h=new Promise(function(g){d=new MutationObserver(function(){var l;return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(n){l=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_tryGetMicrosoftPageFromElements(a);l!==module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.UNKNOWN&&
g(l);n.jumpToEnd()})});d.observe(a.body,{childList:!0,subtree:!0})});return f.yield(Promise.race([e,h]),2)}m=f.yieldResult;(k=d)==null||k.disconnect();clearTimeout(c);return f.return(m)})}
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getMicrosoftPageFromPageid(a){a=a.head.querySelector('meta[name="PageID"]');if(!a||!a.content)return module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.UNKNOWN;if(a.content.toLowerCase().includes("error"))return module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.ERROR;switch(a.content){case "KmsiInterrupt":return module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.STAY_SIGNED_IN;
case "ConvergedSignIn":return module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.SIGN_IN;case "CmsiInterrupt":return module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.DOMAIN_CONFIRMATION;default:return module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.UNKNOWN}}
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getTitleOnDomainConfirmationDialog(a){var b=[a.getElementById("appConfirmTitle"),a.querySelector('div[role="heading"]'),a.querySelector("div.text-title"),Array.from(a.querySelectorAll("div")).find(function(e){var h;return e&&((h=e.textContent)==null?void 0:h.match("^Do you trust (\\S)+?$"))})];a=new Map;b=(0,$jscomp.makeIterator)(b);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.textContent){var d=
void 0;a.set(c,((d=a.get(c))!=null?d:0)+1)}return a.size===0?null:Array.from(a.entries()).reduce(function(e,h){return e[1]>h[1]?e:h})[0].textContent}module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.getTitleOnDomainConfirmationDialog=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getTitleOnDomainConfirmationDialog;
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getContinueButtonOnDomainConfirmationDialog(a){var b=[a.getElementById("idSIButton9"),a.querySelector("input.primary"),a.querySelector("input.button_primary"),a.querySelector('input[type="submit"]'),a.querySelector('input[data-report-value="Submit"]'),a.querySelector('input[value="Continue"]')];a=new Map;b=(0,$jscomp.makeIterator)(b);for(var c=b.next();!c.done;c=b.next())if(c=c.value){var d=void 0;a.set(c,
((d=a.get(c))!=null?d:0)+1)}return a.size===0?null:Array.from(a.entries()).reduce(function(e,h){return e[1]>h[1]?e:h})[0]}module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.getContinueButtonOnDomainConfirmationDialog=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getContinueButtonOnDomainConfirmationDialog;
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_tryGetDomainConfirmationElements(a){var b=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getTitleOnDomainConfirmationDialog(a);a=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getContinueButtonOnDomainConfirmationDialog(a);if(b&&a)return{title:b,button:a}}
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_findDomainConfirmationElements(a){var b,c,d,e,h,m,k;return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(f){if(f.nextAddress==1){if(b=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_tryGetDomainConfirmationElements(a))return f.return(b);e=new Promise(function(g){c=setTimeout(function(){g(void 0)},5E3)});h=new Promise(function(g){d=new MutationObserver(function(){var l;
return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(n){(l=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_tryGetDomainConfirmationElements(a))&&g(l);n.jumpToEnd()})});d.observe(a.body,{childList:!0,subtree:!0})});return f.yield(Promise.race([e,h]),2)}m=f.yieldResult;(k=d)==null||k.disconnect();clearTimeout(c);return f.return(m)})}
module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.findDomainConfirmationElements=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_findDomainConfirmationElements;
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_detectMicrosoftPage(a){var b;return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(c){return c.nextAddress==1?(b=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getMicrosoftPageFromPageid(a),b!==module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.MicrosoftPageType.UNKNOWN?c.return(b):c.yield(module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_getMicrosoftPageWithTimeout(a),
2)):c.return(c.yieldResult)})}module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection.detectMicrosoftPage=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_detectMicrosoftPage;var module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util={ContentScriptMessageType:{DOMAIN_VERIFIED:"domain_verified",PAGE_RESULT:"page_result"}};function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_PageResultMessage(){}module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util.PageResultMessage=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_PageResultMessage;
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_DomainVerifiedMessage(){}module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util.DomainVerifiedMessage=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_DomainVerifiedMessage;
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_sendDomainVerifiedMessage(a,b){b=b===void 0?"":b;return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(c){return c.yield(chrome.runtime.sendMessage({type:module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util.ContentScriptMessageType.DOMAIN_VERIFIED,result:a,error:b}),0)})}
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_escapeRegExp(a){return a.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")}module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util.escapeRegExp=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_escapeRegExp;
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_navigateDomainConfirmationDialog(a,b){var c,d;return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(e){switch(e.nextAddress){case 1:return e.yield(module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_findDomainConfirmationElements(a),2);case 2:c=e.yieldResult;d=new RegExp("\\b"+module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_escapeRegExp(b)+
"\\b");if(c){e.jumpTo(3);break}return e.yield(module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_sendDomainVerifiedMessage(!1,"required HTML elements not found on domain confirmation dialog"),4);case 4:return e.return();case 3:return c.title.match(d)?(c.button.click(),e.yield(new Promise(function(h){window.addEventListener("unload",function k(){module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_sendDomainVerifiedMessage(!0);
window.removeEventListener("unload",k);h()})}),0)):e.yield(module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_sendDomainVerifiedMessage(!1,'Configured domain "'+b+'" not found in title on domain confirmation dialog "'+c.title+'"'),0)}})}
function module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_executeContentScript(a){var b,c;return(0,$jscomp.asyncExecutePromiseGeneratorProgram)(function(d){return d.nextAddress==1?d.yield(module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_page_detection_detectMicrosoftPage(a),2):d.nextAddress!=3?(b=d.yieldResult,d.yield(chrome.runtime.sendMessage({type:module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util.ContentScriptMessageType.PAGE_RESULT,
pageId:b}),3)):(c=d.yieldResult)&&c.proceed&&c.domain?d.yield(module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_navigateDomainConfirmationDialog(a,c.domain),0):d.return()})}module$exports$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util.executeContentScript=module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_executeContentScript;module$contents$google3$chrome$apps$file_manager$odfs$js$auth_third_party_content_script_util_executeContentScript(document);
