# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description "mount modem firmware squashfs file"
author "chromium-os-dev@chromium.org"

start on started boot-services
task

# This is extremely unlikely to run out of memory.
oom score -100

env MODEM_FW_ROOT="/opt/google/modemfwd-firmware"

exec mount -o ro,nodev,noexec,nosuid "${MODEM_FW_ROOT}/modem_fw.squash" \
  "${MODEM_FW_ROOT}"
