# Copyright 2020 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description "Mount Quickoffice squashfs file"
author "chromium-os-dev@chromium.org"

start on started system-services
stop on stopping system-services

oom score never

env ASSETS=/usr/share/chromeos-assets

pre-start script
  if [ -f "${ASSETS}/quickoffice.squash" ]; then
    exec mount -o nodev,noexec,nosuid "${ASSETS}/quickoffice.squash" \
      "${ASSETS}/quickoffice"
  fi
end script

post-stop script
  if [ -f "${ASSETS}/quickoffice.squash" ]; then
    exec umount "${ASSETS}/quickoffice"
  fi
end script
