# Copyright (c) 2018 - 2020 SiliconMotion Inc.

description "SiliconMotion Display Manager Service"
author "SiliconMotion Inc."

oom score -100

expect fork
respawn

exec minijail0 -i -l -r -v --uts -p \
  --profile=minimalistic-mountns \
  -b /sys \
  -b /sys/devices/evdi,,1 \
  -b /dev/ \
  -u smdisplay -g smdisplay \
  -G \
  /opt/siliconmotion/SMIUSBDisplay