# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description     "The teardown logic for hardening the lock screen."
author          "allenwebb@chromium.org"

oom score -100

# These signals are emitted by session_manager.
#
# screen-unlocked may not be called for every screen-locked event, but
# start-user-session covers those cases.
start on (screen-unlocked or start-user-session) and stopped usbguard
task

script
  logger -t "${UPSTART_JOB}" "Unlocking USB."

  systemd-tmpfiles --remove /usr/lib/tmpfiles.d/usb_bouncer.conf

  # Accept new usb devices by default, and authorize connected devices.
  usb_bouncer authorize-all
end script
