// Copyright 2018 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a the GPL license that can be
// found in the LICENSE file.

try {
  importScripts('./constants.js', './language_defaults.js');
} catch (e) {
  console.error('Error importing scripts: ', e);
}

let espeak_engine_ = null;

chrome.runtime.onMessage.addListener(
    /**
     * Handles incoming messages received from `espeak_offscreen.js`, and
     * `options.js`.
     * @param {object!} request Data received from some other process sent via
     *     chrome.runtime.sendMessage.
     * @param {object!} sender An object containing information about the script
     *     context that sent a message or request. Has properties such as
     *     document id, origin, etc.
     * @param {Function!} sendResponse A callback which responds to the sender,
     *     and closes the message channel.
     * @return {boolean|undefined} True if the sendResponse callback will be
     *     called asynchronously, false or undefined otherwise.
     */
    async (request, sender, sendResponse) => {
      if (espeak_engine_ == null && !await init()) {
        console.error(
            'Could not restore service worker while attempting to handle a message from the offscreen document.');
        return;
      }

      if (request == null || request.type == null) {
        console.error('Malformed request: ', request, 'from: ', sender);
        return;
      }

      switch (request.type) {
        case UPDATE_VOICES_MSG:
          espeak_engine_.updateVoices();
          break;
        case HANDLE_EVENTS_MSG:
          espeak_engine_.handleEvents(
              request.utteranceId, request.samples, request.events);
          break;
        case GET_LANG_INFO_ARRAY_MSG:
          let responded = false;
          espeak_engine_.getLangInfoArray((langInfoArray) => {
            sendResponse(langInfoArray);
            responded = true;
          });
          return !responded;
        default:
          break;
      }
    });

// Start listening to chrome.ttsEngine requests.
chrome.ttsEngine.onSpeakWithAudioStream.addListener(
    /**
     * Listener parameters when the ttsEngine receives an utterance request.
     * Parameter definitions mirror `espeak_engine_.onSpeak(..)` defintions,
     * please use that function as a reference.
     */
    async (utterance, options, audioStreamOptions, sendTtsAudio, sendError) => {
      if (espeak_engine_ == null && !await init()) {
        console.error(
            'Could not restore service worker while attempting to handle a speakWithAudioStream event.');
        return;
      }

      espeak_engine_.onSpeak(
          utterance, options, audioStreamOptions, sendTtsAudio, sendError);
    });

// Clean up when audio stops playing.
chrome.ttsEngine.onStop.addListener(() => {
  if (espeak_engine_ == null) {
    // Engine is terminated, so there is no work to do.
    return;
  }

  espeak_engine_.onStop();
});
chrome.ttsEngine.onPause.addListener(() => {});
chrome.ttsEngine.onResume.addListener(() => {});

/**
 * @fileoverview eSpeak text-to-speech extension.
 *
 * There are three components to the extension:
 *
 * The open-source eSpeak-NG engine is compiled using Emscripten into a
 * WebAssembly module that's run in a web worker. The interface to it is
 * stored in this.tts_. This class sends it asynchronous queries for
 * a list of voices and commands to start generating speech. Callbacks
 * from the engine queue up events like word callbacks, and generate
 * audio data.
 *
 * The implementation of the chrome.ttsEngine API is how we get
 * commands to speak and stop. We also use this API to publish the
 * current set of enabled voices.
 *
 * Finally, the audio data generated by the engine is output using
 * a private mojo interface. This is an intermediate solution as will
 * serve as motivation for a new chrome.TtsEngine api.
 */
class EspeakTtsEngine {
  constructor() {
    /**
     * The callback provided by a call to chrome.ttsEngine.onSpeak, which is
     * our channel to send status updates about the progress of speech.
     */
    this.ttsEngineApiCallback_ = null;

    /**
     * The string containing the text we're currently speaking.
     */
    this.utterance_ = null;

    /**
     * An id to track the current utterance to, for example, ensure audio data
     * for previous utterances is ignored.
     */
    this.utteranceId_ = 0;

    /**
     * The handle to the WASM Espeak-NG module.
     */
    this.tts_ = null;

    /** Sample rate requested for Espeak to generate audio. */
    this.sampleRate_;

    /**
     * The size, in samples, of each audio frame. When using an
     * AudioWorkletProcessor this is always 128 samples.
     */
    this.bufferSize_;

    /**
     * The current buffer of audio samples from the engine. When each
     * buffer fills up it's sent to the audio worklet processor thread.
     */
    this.currentBuffer_ = null;

    /**
     * The current zero-based index into |this.currentBuffer_| where the
     * next audio sample should be written.
     */
    this.currentBufferIndex_ = 0;

    /**
     * Whether or not we're currently playing audio.
     * This is not set to true until after we've got at least one
     * buffer worth of samples from the engine and sent it to be played.
     */
    this.playing_ = false;

    /**
     * The voice data for the languages that are supported by eSpeak
     * and enabled by the user. The elements of this array are in the
     * format needed by the chrome.ttsEngine API.
     */
    this.ttsEngineApiVoices_ = [];

    /**
     * The data about each enabled language in eSpeak's format.
     * Used when we get a speech request that specifies a language
     * code but not a specific complete voice name.
     */
    this.internalVoiceInfos_ = [];

    /**
     * The data about every supported eSpeak language, in eSpeak's
     * format. Used by the options page to present all languages to
     * the user and let them choose which ones to enable.
     */
    this.langInfoArray_ = [];

    /**
     * Function to call when langInfoArray_ is populated.
     */
    this.pendingGetLangInfoArrayCallback_ = null;

    /**
     * The default voice to use when no metadata is provided at all.
     */
    this.defaultEspeakVoiceName_ = null;

    /**
     * The timestamp when speech started. Used to fire events like
     * word callbacks.
     */
    this.startTime_ = null;

    /**
     * Callback to run after initialization.
     */
    this.pendingCallback_ = null;

    /**
     * True if initialization is done.
     */
    this.initialized_ = false;

    // Service workers (like this one), cannot spawn dedicated workers.
    // Call the offscreen page to create an instance of dedicated worker for
    // this service worker to use.
    maybeSetupOffscreenDocument().then((contexts) => {
      if (contexts.length > 0) {
        chrome.runtime.sendMessage({type: CREATE_WASM_WORKER_MSG}, (response) => {
          switch (response.type) {
            case CREATE_WASM_WORKER_SUCCESS_MSG:
              break;
            case CREATE_WASM_WORKER_FAILURE_MSG:
            default:
              throw new Error(`Dispatched ${
                  CREATE_WASM_WORKER_MSG} and received: ${response.type}`);
              break;
          }
        });
      }
    });
  }

  /**
   * Return the array of all languages supported by eSpeak. Called by
   * the options page.
   */
  getLangInfoArray(callback) {
    if (this.langInfoArray_.length > 0) {
      callback(this.langInfoArray_);
      return;
    }

    this.pendingGetLangInfoArrayCallback_ = callback;
  };

  /**
   * Function called on startup and when the set of enabled voices
   * may have changed.
   */
  updateVoices() {
    console.log('updateVoices');
    chrome.runtime.sendMessage(
        {type: LIST_VOICES_MSG},
        ((langInfoArray) => {
          this.langInfoArray_ = langInfoArray;
          // Remove Japanese because the voice cannot pronounce many characters.
          for (let i = 0; i < this.langInfoArray_.length; ++i) {
            if (this.langInfoArray_[i].identifier === 'jpx/ja') {
              this.langInfoArray_.splice(i, 1);
              break;
            }
          }
          this.ttsEngineApiVoices_ = [];
          this.internalVoiceInfos_ = [];
          this.langsRemaining_ = this.langInfoArray_.length;
          this.langInfoArray_.forEach(
              (function(langInfo) {
                isEspeakLanguageEnabled(
                    langInfo,
                    (function(enabled) {
                      if (enabled) {
                        let voiceName = 'eSpeak ' + langInfo.name;
                        let ttsEngineApiVoice = {
                          voiceName: voiceName,
                          lang: langInfo.languages[0].name,
                          remote: false,
                          eventTypes:
                              ['start', 'end', 'word', 'sentence', 'error']
                        };
                        this.ttsEngineApiVoices_.push(ttsEngineApiVoice);

                        let internalVoiceInfo = {
                          voiceName: voiceName,
                          espeakVoiceName: langInfo.name,
                          languages: langInfo.languages
                        };
                        this.internalVoiceInfos_.push(internalVoiceInfo);
                      }

                      this.langsRemaining_--;
                      if (this.langsRemaining_ == 0) {
                        this.finishInitialization_();
                      }
                    }).bind(this));
              }).bind(this));
          if (this.pendingGetLangInfoArrayCallback_) {
            this.pendingGetLangInfoArrayCallback_(this.langInfoArray_);
            this.pendingGetLangInfoArrayCallback_ = null;
          }
        }).bind(this));
  };

  /**
   * Called after asynchronously getting the list of languages
   * supported by eSpeak and filtering it to only the ones
   * currently enabled and converting that to the format expected
   * by the chrome.ttsEngine API.
   *
   * Calls chrome.ttsEngine.updateVoices to advertise the set of
   * voices currently enabled, and updates the default voice to
   * be used if someone requests speech without specifying any
   * other metadata.
   */
  finishUpdatingVoices_() {
    console.log('finishUpdatingVoices_');
    chrome.ttsEngine.updateVoices(this.ttsEngineApiVoices_);
    console.log(`Loaded ${this.ttsEngineApiVoices_.length} voices`);

    this.defaultEspeakVoiceName_ =
        this.getBestEspeakVoice('', navigator.language);
  };

  /**
   * Finish initialization by initializing the playback system.
   * This is the final step, then we can start speaking.
   */
  finishInitialization_() {
    this.finishUpdatingVoices_();

    // Initialization is now complete.
    this.initialized_ = true;
    if (this.pendingCallback_) {
      this.pendingCallback_();
      this.pendingCallback_ = null;
    }
  }

  /**
   * Called by the client to stop speech.
   */
  onStop() {
    this.onStopInternal();
  }

  onStopInternal() {
    this.pendingCallback_ = null;

    this.playing_ = false;
    this.ttsEngineApiCallback_ = null;
  };

  /**
   * Helper function which determines whether a sample is at it's end.
   * If the sample still has data, the sample is processed in a separate helper.
   *
   * @param {number} utteranceId The id of the utterance that the audio buffer is
   *     for. If the utteranceId is different, the sample is ignored.
   * @param {ArrayBuffer?} samples The raw audio data in the form of a
   *     Float32Array.
   * @param {Array?} events Type of events for each character index.
   */
  handleEvents(utteranceId, samples, events) {
    if (this.utteranceId_ != utteranceId) {
      return;
    }

    // 'end' type events can still be followed by audio data. This is a more
    // reliable way the native code signals end.
    let isEnd = events === undefined;
    let charIndex = -1;

    if (events) {
      for (const event of events) {
        charIndex = event.text_position;

        switch (event.type) {
          case 'sentence':
          case 'word':
          case 'end':
            break;
        }
      }
    }
    const sampleArray = new Float32Array(samples);
    this.processSamples(sampleArray, charIndex, isEnd);
  }

  /**
   * Called by the client to start speech synthesis.
   *
   * @param {string} utterance The utterance to say.
   * @param {object!} options The options affecting the speech, like language,
   *   pitch, rate, etc.
   * @param {object?} audioStreamOptions Various voice settings, such as sampleRate or
   *     bufferSize.
   * @param {function(object?)} sendTtsAudio The function to receive messages from
   *     the engine.
   * @param {function(string)} sendError The function to receive error messages
   *     from the engine.
   */
  onSpeak(utterance, options, audioStreamOptions, sendTtsAudio, sendError) {
    console.log(`Will speak: "${utterance}" lang="${options.lang}"`);
    this.utteranceId_++;
    this.pendingCallback_ = null;

    if (!this.initialized_) {
      // We got a call to speak before we're initialized. Enqueue this until
      // we're ready.
      this.pendingCallback_ = this.onSpeak.bind(this, ...arguments);
      return;
    }

    this.ttsEngineApiCallback_ = sendTtsAudio;
    this.utterance_ = utterance;

    this.sampleRate_ = audioStreamOptions.sampleRate;
    this.bufferSize_ = audioStreamOptions.bufferSize;

    const espeakVoiceName =
        this.getBestEspeakVoice(options.voiceName, options.lang);
    chrome.runtime.sendMessage({type: SET_VOICE_MSG, voiceName: espeakVoiceName});

    chrome.runtime.sendMessage(
        {type: SET_SYSTEM_SAMPLE_RATE_MSG, sampleRate: this.sampleRate_});

    // Chrome TTS rates range from 0.1 to 10.0, with 1.0 as the default.
    // eSpeak rates range from 80 to 450, with 175 as the default.
    const rate = Math.min(Math.max(Math.floor(options.rate * 175), 80), 450);
    chrome.runtime.sendMessage({type: SET_RATE_MSG, rate: rate});

    // Chrome TTS pitches range from 0.0 to 2.0, with 1.0 as the default.
    // eSpeak pitches range from 0 to 99, with 50 as the default.
    const pitch = Math.min(Math.max(Math.floor(options.pitch * 50), 0), 99);
    chrome.runtime.sendMessage({type: SET_PITCH_MSG, pitch: pitch});

    chrome.runtime.sendMessage({
      type: SYNTHESIZE_MSG,
      utterance: utterance,
      utteranceId: this.utteranceId_
    });
  };

  /**
   * Given a voice name and language, determine the best eSpeak voice
   * to use. Sometimes a partial match needs to be used, for example
   * because the language requested is just 'en', but eSpeak has
   * 'en-US', 'en-GB', etc.
   */
  getBestEspeakVoice(desiredVoiceName, desiredLang) {
    let exactMatchEspeakVoiceName = null;
    let langMatchEspeakVoiceName = null;
    let langMatch = '';
    this.internalVoiceInfos_.forEach(
        (function(voice) {
          if (desiredVoiceName == voice.voiceName)
            exactMatchEspeakVoiceName = voice.espeakVoiceName;
          voice.languages.forEach(
              (function(lang) {
                if (desiredLang.toLowerCase() == lang.name.toLowerCase() &&
                    lang.name.length > langMatch.length) {
                  langMatch = lang.name;
                  langMatchEspeakVoiceName = voice.voiceName;
                }
              }).bind(this));
        }).bind(this));

    if (exactMatchEspeakVoiceName) return exactMatchEspeakVoiceName;

    if (langMatchEspeakVoiceName) return langMatchEspeakVoiceName;

    return this.defaultEspeakVoiceName_;
  };

  /**
   * Called when we get samples back from the WebAssembly TTS engine.
   * Fills up buffers with samples, and as each buffer fills, sends it to be
   * played.
   *
   * If these are the first samples for a new utterance, starts speech
   * by connceting the audio node.
   */
  processSamples(samples, charIndex, isEnd) {
    if (!this.ttsEngineApiCallback_) {
      return;
    }

    let i = 0;
    const len = samples.length;

    let didSendBuffers = false;
    while (i < len) {
      const chunkLen =
          Math.min(this.bufferSize_ - this.currentBufferIndex_, len - i);
      if (!this.currentBuffer_) {
        this.currentBuffer_ = new Float32Array(this.bufferSize_);
      }
      this.currentBuffer_.set(
          samples.subarray(i, i + chunkLen), this.currentBufferIndex_);
      i += chunkLen;
      this.currentBufferIndex_ += chunkLen;
      if (this.currentBufferIndex_ == this.bufferSize_) {
        this.ttsEngineApiCallback_(
            {audioBuffer: this.currentBuffer_, charIndex, isLastBuffer: isEnd});
        didSendBuffers = true;
        charIndex = -1;

        this.currentBufferIndex_ = 0;
        this.currentBuffer_ = null;
      }
    }

    // Push final buffer, not complete.
    if (isEnd && this.currentBufferIndex_ > 0) {
      this.ttsEngineApiCallback_(
          {audioBuffer: this.currentBuffer_, charIndex, isLastBuffer: isEnd});
      didSendBuffers = true;
      this.currentBufferIndex_ = 0;
      this.currentBuffer_ = null;
    }

    // Connect and start playback if this is the
    // first buffer.
    if (didSendBuffers && !this.playing_) {
      this.playing_ = true;
      this.startTime_ = new Date();
    }
  }
}

/**
 * Creates a new offscreen document if one doesn't already exist. If it does,
 * this function results in a no-op.
 *
 * @return {array!} Returns an array of ExtensionContexts objects. The array can
 *     be empty if the offscreen document failed to initialize.
 */
async function maybeSetupOffscreenDocument() {
  try {
    // Check if an offscreen document is already active, and return it.
    let existingContexts = await chrome.runtime.getContexts({
      contextTypes: ['OFFSCREEN_DOCUMENT'],
      documentUrls: [chrome.runtime.getURL(OFFSCREEN_DOCUMENT_PATH)]
    });

    if (existingContexts.length > 0) {
      return existingContexts;
    }

    // Otherwise, create a new offscreen document, and return that instead.
    await chrome.offscreen.createDocument({
      url: OFFSCREEN_DOCUMENT_PATH,
      reasons: [chrome.offscreen.Reason.WORKERS],
      justification:
          'Main page which handles communication between Extension Service Worker and eSpeakNG Dedicated Worker.',
    });

    existingContexts = await chrome.runtime.getContexts({
      contextTypes: ['OFFSCREEN_DOCUMENT'],
      documentUrls: [chrome.runtime.getURL(OFFSCREEN_DOCUMENT_PATH)]
    });

    return existingContexts;
  } catch (e) {
    console.error('Could not create offscreen document: ', e);
    return [];
  }
}

/**
 * Creates a new EspeakTTSEngine, and then stores it in an offscreen page which
 * will be used by the options.html page.
 *
 * @return {boolean} Whether an instance of EspeakTtsEngine() was initialized
 *     successfully.
 */
async function init() {
  // In 'split' manifest mode, the extension system runs two copies of the
  // extension. One in an incognito context; the other not. In guest mode, the
  // extension system runs only the extension in an incognito context. To
  // prevent doubling of this extension, only continue for one context.
  const manifest =
      /** @type {{incognito: (string|undefined)}} */ (
          chrome.runtime.getManifest());
  if (manifest.incognito !== 'split' || chrome.extension.inIncognitoContext) {
    // Create an offscreen document if needed. This will be used to store the
    // engine.
    const existingContexts = await maybeSetupOffscreenDocument();

    if (existingContexts.length === 0) {
      console.error(
          'Failed to create offscreen page, so Espeak TTS engine cannot be initialized.');
      return false;
    }

    // Initialize the engine.
    espeak_engine_ = new EspeakTtsEngine();

    return true;
  }

  // Do nothing and let the system automatically end this service worker.
  return false;
}

// Create the TTSEngine in the Chrome Extension.
init();
