# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[fwupd Remote]
Enabled=true
Title=fwupd-peripherals
Type=local
Keyring=none
MetadataURI=file:///usr/share/fwupd/remotes.d/vendor/fwupd-peripherals.metainfo.xml.gz
FirmwareBaseURI=https://storage.googleapis.com/chromeos-localmirror/lvfs/
ApprovalRequired=false
