var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};
$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};var DEBUG=!1;function TextApp(){this.windowController_=this.settingsController_=this.searchController_=this.menuController_=this.hotkeysController_=this.dialogController_=this.tabs_=this.settings_=this.editor_=null;this.hasFrame_=!1}TextApp.prototype.init=function(){this.settings_=new Settings;this.editor_=null;if(this.settings_.isReady())this.onSettingsReady_();else $(document).bind("settingsready",this.onSettingsReady_.bind(this));$(document).bind("settingschange",this.onSettingsChanged_.bind(this))};
TextApp.prototype.openTabs=function(a){for(var b=0;b<a.length;b++)this.tabs_.openFileEntry(a[b]);this.windowController_.focus_();this.tabs_.hasOpenTab()||this.tabs_.newTab()};TextApp.prototype.setHasChromeFrame=function(a){this.hasFrame_=a;this.windowController_.windowControlsVisible(!a)};TextApp.prototype.getFilesToRetain=function(){return this.tabs_.getFilesToRetain()};TextApp.prototype.setTheme=function(){var a=this.settings_.get("theme");this.windowController_.setTheme(a);this.editor_.setTheme(a)};
TextApp.prototype.onSettingsReady_=function(){this.settingsController_=new SettingsController(this.settings_);this.initEditor_();this.windowController_.setAlwaysOnTop(this.settings_.get("alwaysontop"));chrome.runtime.getBackgroundPage(function(a){a.background.onWindowReady(this)}.bind(this))};
TextApp.prototype.initControllers_=function(){this.dialogController_=new DialogController($("#dialog-container"),this.editor_);this.tabs_=new Tabs(this.editor_,this.dialogController_,this.settings_);this.menuController_=new MenuController(this.tabs_);this.windowController_=new WindowController(this.editor_,this.settings_,this.tabs_);this.hotkeysController_=new HotkeysController(this.windowController_,this.tabs_,this.editor_,this.settings_,this.settingsController_);this.searchController_=new SearchController(this.editor_.getSearch())};
TextApp.prototype.loadSettingsIntoEditor=function(){this.setTheme();this.editor_.applyAllSettings()};TextApp.prototype.initEditor_=function(){if(this.editor_)console.error("Trying to re-initialize text app");else{var a=document.getElementById("editor");this.editor_=new EditorCodeMirror(a,this.settings_);this.initControllers_();this.loadSettingsIntoEditor()}};
TextApp.prototype.onSettingsChanged_=function(a,b,c){switch(b){case "alwaysontop":this.windowController_.setAlwaysOnTop(c);break;case "fontsize":this.editor_.setFontSize(c);break;case "linenumbers":this.editor_.showHideLineNumbers(c);break;case "spacestab":this.editor_.setReplaceTabWithSpaces(this.settings_.get("spacestab"));break;case "tabsize":this.editor_.setTabSize(c);break;case "theme":this.setTheme();break;case "wraplines":this.editor_.setWrapLines(c)}};var textApp=new TextApp;
document.addEventListener("DOMContentLoaded",function(){textApp.init()});function EditorCodeMirror(a,b){var c=window.CodeMirror;this.element_=a;this.settings_=b;this.editableCompartment_=new c.state.Compartment;this.tabSizeCompartment_=new c.state.Compartment;this.indentUnitCompartment_=new c.state.Compartment;this.langCompartment_=new c.state.Compartment;this.lineWrappingCompartment_=new c.state.Compartment;this.lineNumbersCompartment_=new c.state.Compartment;this.themeCompartment_=new c.state.Compartment;var d={"&":{backgroundColor:"var(--ta-background-color)",color:"var(--ta-editor-text-color)"},
".cm-content":{fontSize:"var(--ta-editor-font-size)",lineHeight:"1.2"},".cm-gutter":{backgroundColor:"var(--ta-background-color)",color:"var(--ta-editor-line-number-text-color)",fontSize:"var(--ta-editor-font-size)",lineHeight:"1.2"},".cm-cursor":{borderLeftColor:"var(--ta-editor-text-color)"},".cm-dropCursor":{borderLeftColor:"var(--ta-editor-text-color)"},"&.cm-focused .cm-selectionBackground":{backgroundColor:"var(--ta-editor-selection-focus-color) !important"},".cm-selectionBackground":{backgroundColor:"var(--ta-editor-selection-color) !important"},
".cm-matchingBracket":{backgroundColor:"inherit !important",color:"var(--ta-editor-text-color) !important",borderBottom:"1px solid var(--ta-editor-text-color)"},".cm-nonmatchingBracket":{backgroundColor:"inherit !important"},".cm-line":{cursor:"auto"}};this.lightTheme_=c.view.EditorView.theme(d,{dark:!1});this.darkTheme_=c.view.EditorView.theme(d,{dark:!0});this.editorView_=new c.view.EditorView({doc:"",parent:a});this.search_=new Search(this.editorView_)}
EditorCodeMirror.EXTENSION_TO_MODE={bash:"shell",coffee:"coffeeScript",c:"cpp","c++":"cpp",cc:"cpp",cs:"cpp",css:"css",cpp:"cpp",cxx:"cpp",diff:"diff",gemspec:"ruby",go:"go",h:"cpp",hh:"cpp",hpp:"cpp",htm:"html",html:"html",java:"java",js:"javascript",json:"json",latex:"stex",less:"less",ltx:"stex",lua:"lua",markdown:"markdown",md:"markdown",patch:"diff",pgsql:"sql",pl:"perl",pm:"perl",php:"php",phtml:"php",py:"python",rb:"ruby",rdf:"xml",rs:"rust",rss:"xml",ru:"ruby",sh:"shell",sql:"sql",svg:"xml",
tex:"stex",xhtml:"html",xml:"xml",yaml:"yaml"};var t=window.CodeMirror.highlight.tags;
EditorCodeMirror.HIGHLIGHT_STYLE=window.CodeMirror.language.HighlightStyle.define([{tag:t.variableName,color:"var(--ta-token-variable-color)"},{tag:t.definition(t.variableName),color:"var(--ta-token-definition-color)"},{tag:t.propertyName,color:"var(--ta-token-property-color)"},{tag:[t.typeName,t.className,t.namespace,t.macroName],color:"var(--ta-token-type-color)"},{tag:[t.special(t.name),t.constant(t.className)],color:"var(--ta-token-variable-special-color)"},{tag:t.standard(t.variableName),color:"var(--ta-token-builtin-color)"},
{tag:[t.number,t.literal,t.unit],color:"var(--ta-token-number-color)"},{tag:t.string,color:"var(--ta-token-string-color)"},{tag:[t.special(t.string),t.regexp,t.escape],color:"var(--ta-token-string-special-color)"},{tag:[t.atom,t.unit,t.labelName,t.bool],color:"var(--ta-token-atom-color)"},{tag:t.keyword,color:"var(--ta-token-keyword-color)"},{tag:[t.comment,t.quote],color:"var(--ta-token-comment-color)"},{tag:t.invalid,backgroundColor:"var(--ta-token-invalid-background-color)",color:"var(--ta-token-invalid-color) !important"},
{tag:t.meta,color:"var(--ta-token-meta-color)"},{tag:t.tagName,color:"var(--ta-token-tag-color)"},{tag:t.attributeName,color:"var(--ta-token-attribute-color)"},{tag:t.attributeValue,color:"var(--ta-token-attribute-value-color)"},{tag:t.heading,color:"var(--ta-token-heading-color)"},{tag:t.quote,color:"var(--ta-token-quote-color)"},{tag:t.link,color:"var(--ta-token-link-color)"},{tag:t.url,color:"var(--ta-token-url-color)"},{tag:t.inserted,color:"var(--ta-token-inserted-color)"},{tag:t.deleted,color:"var(--ta-token-deleted-color)"},
{tag:t.contentSeparator,color:"var(--ta-token-content-separator-color)"},{tag:t.strong,fontWeight:"bold"},{tag:t.emphasis,fontStyle:"italic"}]);
EditorCodeMirror.prototype.newState=function(a){var b=this,c=window.CodeMirror;return c.state.EditorState.create({doc:a||"",extensions:[c.commands.history({minDepth:1E4}),c.view.drawSelection(),c.view.dropCursor(),c.language.bracketMatching(),this.langCompartment_.of(c.lang.javascript()),this.lineNumbersCompartment_.of(c.view.lineNumbers()),c.view.keymap.of([{key:"Enter",run:function(d){var e=d.state;d=d.dispatch;if(b.settings_.get("smartindent"))return window.CodeMirror.commands.insertNewlineAndIndent({state:e,
dispatch:d});if(e.readOnly)return!1;var f=e.changeByRange(function(h){var g=h.from;h=h.to;for(var k=e.doc.lineAt(g),l=window.CodeMirror.state.countColumn(/^\s*/.exec(e.doc.lineAt(g).text)[0],e.tabSize);h<k.to&&/\s/.test(k.text[h-k.from]);)h++;g>k.from&&g<k.from+100&&!/\S/.test(k.text.slice(0,g))&&(g=k.from);k=["",window.CodeMirror.language.indentString(e,l)];return{changes:{from:g,to:h,insert:window.CodeMirror.state.Text.of(k)},range:window.CodeMirror.state.EditorSelection.cursor(g+1+k[1].length)}});
d(e.update(f,{scrollIntoView:!0,userEvent:"input"}));return!0}}].concat($jscomp.arrayFromIterable(c.commands.defaultKeymap),$jscomp.arrayFromIterable(c.commands.historyKeymap),[{key:"Tab",preventDefault:!0,run:function(d){var e=d.state;d=d.dispatch;if(!b.settings_.get("spacestab"))return window.CodeMirror.commands.insertTab({state:e,dispatch:d});if(e.selection.ranges.some(function(g){return!g.empty}))return window.CodeMirror.commands.indentMore({state:e,dispatch:d});var f=new window.CodeMirror.language.IndentContext(e),
h=f.column(e.selection.main.head);f=f.unit;d(e.update(e.replaceSelection(" ".repeat(f-h%f)),{scrollIntoView:!0,userEvent:"input"}));return!0}},{key:"Shift-Tab",preventDefault:!0,run:c.commands.indentSelection},{key:"Ctrl-d",run:c.commands.deleteLine}])),this.editableCompartment_.of(c.view.EditorView.editable.of(!0)),this.tabSizeCompartment_.of(c.state.EditorState.tabSize.of(2)),this.indentUnitCompartment_.of(window.CodeMirror.language.indentUnit.of("  ")),this.lineWrappingCompartment_.of(c.view.EditorView.lineWrapping),
c.view.EditorView.updateListener.of(this.onViewUpdate.bind(this)),c.search.search({literal:!0}),this.themeCompartment_.of(this.lightTheme_),c.language.syntaxHighlighting(EditorCodeMirror.HIGHLIGHT_STYLE)]})};EditorCodeMirror.prototype.setSession=function(a,b){this.editorView_.setState(a);this.applyAllSettings();this.updateMode(b)};EditorCodeMirror.prototype.getSearch=function(){return this.search_};EditorCodeMirror.prototype.focus=function(){this.editorView_.focus()};
EditorCodeMirror.prototype.updateMode=function(a){var b;if(a=EditorCodeMirror.EXTENSION_TO_MODE[a])a=window.CodeMirror.lang[a],"object"===typeof a?b=window.CodeMirror.language.StreamLanguage.define(a):"function"===typeof a&&(b=a());void 0!==b?this.editorView_.dispatch({effects:this.langCompartment_.reconfigure(b)}):this.editorView_.dispatch({effects:this.langCompartment_.reconfigure([])})};
EditorCodeMirror.prototype.applyAllSettings=function(){this.setTheme(this.settings_.get("theme"));this.setFontSize(this.settings_.get("fontsize"));this.showHideLineNumbers(this.settings_.get("linenumbers"));this.setReplaceTabWithSpaces(this.settings_.get("spacestab"));this.setTabSize(this.settings_.get("tabsize"));this.setWrapLines(this.settings_.get("wraplines"))};EditorCodeMirror.prototype.setFontSize=function(a){this.element_.style.setProperty("--ta-editor-font-size",a+"px");this.editorView_.setState(this.editorView_.state)};
EditorCodeMirror.prototype.setTabSize=function(a){var b=this.settings_.get("spacestab");this.editorView_.dispatch({effects:[this.tabSizeCompartment_.reconfigure(window.CodeMirror.state.EditorState.tabSize.of(a)),this.getIndentUnitStateEffect(b,a)]})};EditorCodeMirror.prototype.getIndentUnitStateEffect=function(a,b){var c=a?" ".repeat(b):"\t";return this.indentUnitCompartment_.reconfigure(window.CodeMirror.language.indentUnit.of(c))};
EditorCodeMirror.prototype.setTheme=function(a){this.editorView_.dispatch({effects:this.themeCompartment_.reconfigure("dark"===a?this.darkTheme_:this.lightTheme_)})};EditorCodeMirror.prototype.showHideLineNumbers=function(a){this.editorView_.dispatch({effects:this.lineNumbersCompartment_.reconfigure(a?window.CodeMirror.view.lineNumbers():[])})};
EditorCodeMirror.prototype.setWrapLines=function(a){this.editorView_.dispatch({effects:this.lineWrappingCompartment_.reconfigure(a?window.CodeMirror.view.EditorView.lineWrapping:[])})};EditorCodeMirror.prototype.setReplaceTabWithSpaces=function(a){var b=this.settings_.get("tabsize");this.editorView_.dispatch({effects:[this.getIndentUnitStateEffect(a,b)]})};EditorCodeMirror.prototype.onViewUpdate=function(a){a.docChanged&&$.event.trigger("docchange")};EditorCodeMirror.prototype.disable=function(){this.editorView_.dispatch({effects:this.editableCompartment_.reconfigure(window.CodeMirror.view.EditorView.editable.of(!1))})};
EditorCodeMirror.prototype.enable=function(){this.editorView_.dispatch({effects:this.editableCompartment_.reconfigure(window.CodeMirror.view.EditorView.editable.of(!0))})};var i18nTemplate=function(){function a(e){e=e.querySelectorAll(d);for(var f,h=0;f=e[h];h++)for(var g=0;g<c.length;g++){var k=c[g],l=f.getAttribute(k);if(null!=l)b[k](f,l)}}var b={"i18n-content":function(e,f){e.textContent=chrome.i18n.getMessage(f)},"i18n-values":function(e,f){f.replace(/\s/g,"").split(/;/).forEach(function(h){if(h)if(h=h.match(/^([^:]+):(.+)$/)){var g=h[1];h=chrome.i18n.getMessage(h[2]);if("."==g[0]){g=g.slice(1).split(".");for(var k=e;k&&1<g.length;)k=k[g.shift()];k&&(k[g]=h,"innerHTML"==
g&&a(e))}else e.setAttribute(g,h)}else console.error("malformed i18n-values: "+f)})}},c=Object.keys(b),d="["+c.join("],[")+"]";return{process:a}}();$(document).ready(i18nTemplate.process(document));function Search(a){this.editorView_=a;this.query_="";this.resultsCount_=this.index_=0}Search.prototype.computeResultsCount_=function(a){a=a.toLowerCase();this.resultsCount_=this.index_=0;if(a)for(var b=this.editorView_.state.selection.main.anchor,c=$jscomp.makeIterator(this.editorView_.state.doc.iterLines()),d=c.next();!d.done;d=c.next()){d=d.value.toLowerCase();for(var e=0;;){e=d.indexOf(a,e);if(0>e)break;this.resultsCount_++;e<b&&this.index_++;e+=a.length}b-=d.length+1}};
Search.prototype.resetSelection_=function(){this.editorView_.dispatch({selection:window.CodeMirror.state.EditorSelection.single(this.editorView_.state.selection.main.anchor)})};Search.prototype.activate=function(){this.resetSelection_();window.CodeMirror.search.openSearchPanel(this.editorView_)};Search.prototype.deactivate=function(){this.find("");window.CodeMirror.search.closeSearchPanel(this.editorView_)};Search.prototype.getCurrentIndex=function(){return 0===this.resultsCount_?0:this.index_+1};
Search.prototype.getResultsCount=function(){return this.resultsCount_};Search.prototype.find=function(a){this.query_=a;this.editorView_.dispatch({effects:window.CodeMirror.search.setSearchQuery.of(new window.CodeMirror.search.SearchQuery({search:a,caseSensitive:!1,literal:!0}))});this.computeResultsCount_(a);this.resetSelection_();this.resultsCount_&&(this.index_--,this.findNext(!1))};
Search.prototype.findNext=function(a){a?(this.index_+=this.resultsCount_-1,window.CodeMirror.search.findPrevious(this.editorView_)):(this.index_++,window.CodeMirror.search.findNext(this.editorView_));this.index_%=this.resultsCount_};Search.prototype.getQuery=function(){return this.query_};Search.prototype.unfocus=function(){this.editorView_.focus()};function Settings(){var a=this;this.ready_=!1;this.settings_={};var b={},c;for(c in Settings.SETTINGS)this.settings_[c]=Settings.SETTINGS[c]["default"],b["settings-"+c]=this.settings_[c];this.storage_=chrome.storage[Settings.AREA];chrome.storage.onChanged.addListener(this.onChanged_.bind(this));chrome.runtime.onInstalled.addListener(this.removeOldSettings_.bind(this));this.storage_.get(b,this.getSettingsCallback_.bind(this));this.colorSchemeMatcherDark_=window.matchMedia("(prefers-color-scheme: dark)");
this.colorSchemeMatcherDark_.addEventListener("change",function(){"default"===a.settings_.theme&&$.event.trigger("settingschange",["theme",a.get("theme")])})}Settings.AREA="sync";
Settings.SETTINGS={alwaysontop:{"default":!1,type:"boolean",widget:"checkbox"},fontsize:{"default":14,type:"number",widget:"number"},linenumbers:{"default":!0,type:"boolean",widget:"checkbox"},sidebaropen:{"default":!1,type:"boolean",widget:null},sidebarwidth:{"default":220,type:"integer",widget:null},smartindent:{"default":!0,type:"boolean",widget:"checkbox"},spacestab:{"default":!0,type:"boolean",widget:"checkbox"},tabsize:{"default":4,type:"integer",widget:"number"},theme:{"default":"default",
type:"string",widget:"radio"},wraplines:{"default":!0,type:"boolean",widget:"checkbox"},search:{"default":!0,type:"boolean",widget:"search"}};Settings.prototype.removeOldSettings_=function(){"autosave"in this.settings_&&delete this.settings_.autosave;this.storage_.remove("autosave")};Settings.prototype.get=function(a){var b=this.settings_[a];return"theme"===a&&"default"===b?this.colorSchemeMatcherDark_.matches?"dark":"light":b};Settings.prototype.getAll=function(){return this.settings_};
Settings.prototype.set=function(a,b){var c={};c["settings-"+a]=b;this.storage_.set(c)};Settings.prototype.reset=function(a){this.set(a,Settings.SETTINGS[a]["default"])};Settings.prototype.isReady=function(){return this.ready_};Settings.prototype.getSettingsCallback_=function(a){this.ready_=!0;for(var b in a){var c=a[b];b=b.substring(9);this.settings_[b]=c}$.event.trigger("settingsready")};
Settings.prototype.onChanged_=function(a,b){if(b!==Settings.AREA)console.warn("Storage change in wrong area. Maybe a bug?");else for(var c in a)if(0===c.indexOf("settings-")){var d=a[c].newValue;c=c.substring(9);console.log("Settings changed:",c,d);this.settings_[c]=d;$.event.trigger("settingschange",[c,d])}};function Tab(a,b,c,d,e){this.id_=a;this.session_=b;this.lineEndings_=c;this.entry_=d;this.saved_=!0;this.path_=null;this.dialogController_=e;this.entry_&&this.updatePath_()}Tab.prototype.getId=function(){return this.id_};Tab.prototype.getName=function(){return this.entry_?this.entry_.name:"Untitled "+this.id_};Tab.prototype.getExtension=function(){return this.entry_?util.getExtension(this.getName()):null};Tab.prototype.getSession=function(){return this.session_};
Tab.prototype.setSession=function(a){return this.session_=a};Tab.prototype.setEntry=function(a){var b=this.getName()!=a.name;this.entry_=a;b&&$.event.trigger("tabrenamed",this);this.updatePath_()};Tab.prototype.getEntry=function(){return this.entry_};Tab.prototype.getPath=function(){return this.path_};Tab.prototype.updatePath_=function(){chrome.fileSystem.getDisplayPath(this.entry_,function(a){this.path_=a;$.event.trigger("tabpathchange",this)}.bind(this))};Tab.prototype.getContent_=function(){return this.session_.doc.toString().split("\n").join(this.lineEndings_)};
Tab.prototype.save=function(a){util.writeFile(this.entry_,this.getContent_(),function(){this.saved_=!0;$.event.trigger("tabsave",this);a&&a()}.bind(this),this.reportWriteError_.bind(this))};Tab.prototype.reportWriteError_=function(a){this.dialogController_.setText("Error saving file: "+util.fsErrorStr(a));this.dialogController_.resetButtons();this.dialogController_.addButton("ok",chrome.i18n.getMessage("okDialogButton"));this.dialogController_.show()};Tab.prototype.isSaved=function(){return this.saved_};
Tab.prototype.changed=function(){this.saved_&&(this.saved_=!1,$.event.trigger("tabchange",this))};function Tabs(a,b,c){this.editor_=a;this.dialogController_=b;this.settings_=c;this.tabs_=[];this.currentTab_=null;$(document).bind("docchange",this.onDocChanged_.bind(this))}
Tabs.prototype.chooseEntry=function(a,b){a.acceptsMultiple?console.error("acceptsMultiple is not supported when saving a file"):chrome.fileSystem.chooseEntry(a,function(c){c&&chrome.runtime.getBackgroundPage(function(d){d.background.copyFileEntry(c,b)})})};Tabs.prototype.chooseEntries=function(a,b,c){a.acceptsMultiple=!0;chrome.fileSystem.chooseEntry(a,function(d){d?chrome.runtime.getBackgroundPage(function(e){for(var f=0;f<d.length;f++)e.background.copyFileEntry(d[f],b)}):c&&c()})};
Tabs.prototype.getTabById=function(a){for(var b=0;b<this.tabs_.length;b++)if(this.tabs_[b].getId()===a)return this.tabs_[b];return null};Tabs.prototype.getCurrentTab=function(){return this.currentTab_};Tabs.prototype.newWindow=function(){chrome.runtime.getBackgroundPage(function(a){a.background.newWindow()}.bind(this))};
Tabs.prototype.newTab=function(a,b){for(var c=1;this.getTabById(c);)c++;var d=this.editor_.newState(a),e=util.guessLineEndings(a);c=new Tab(c,d,e,b||null,this.dialogController_);this.tabs_.push(c);$.event.trigger("newtab",c);this.showTab(c.getId())};Tabs.prototype.reorder=function(a,b){this.tabs_.splice(b,0,this.tabs_.splice(a,1)[0])};Tabs.prototype.getTabIndex=function(a){for(var b=0;b<this.tabs_.length;b++)if(this.tabs_[b]===a)return b;return-1};
Tabs.prototype.previousTab=function(){var a=this.getTabIndex(this.currentTab_)-1;0>a&&(a=this.tabs_.length-1);this.showTab(this.tabs_[a].getId())};Tabs.prototype.nextTab=function(){var a=this.getTabIndex(this.currentTab_)+1;a>=this.tabs_.length&&(a=0);this.showTab(this.tabs_[a].getId())};
Tabs.prototype.showTab=function(a){this.currentTab_&&this.updateCurrentTabState_();var b=this.getTabById(a);b?(this.editor_.setSession(b.getSession(),b.getExtension()),this.currentTab_=b,$.event.trigger("switchtab",b),this.editor_.focus()):console.error("Can't find tab",a)};
Tabs.prototype.close=function(a){for(var b=0;b<this.tabs_.length&&this.tabs_[b].getId()!=a;b++);if(b>=this.tabs_.length)console.error("Can't find tab",a);else{var c=this.tabs_[b];c.isSaved()?this.closeTab_(c):this.promptSave_(c,function(d){"yes"===d?this.save(c,this.closeTab_.bind(this,c)):"no"===d&&this.closeTab_(c)}.bind(this))}};
Tabs.prototype.closeTab_=function(a){a===this.currentTab_&&(1<this.tabs_.length?this.nextTab():window.close());for(var b=0;b<this.tabs_.length&&this.tabs_[b]!==a;b++);this.tabs_.splice(b,1);$.event.trigger("tabclosed",a)};Tabs.prototype.updateCurrentTabState_=function(){this.currentTab_&&this.currentTab_.setSession(this.editor_.editorView_.state)};Tabs.prototype.closeCurrent=function(){this.close(this.currentTab_.getId())};
Tabs.prototype.openFiles=function(){this.chooseEntries({type:"openWritableFile"},this.openFileEntry.bind(this))};Tabs.prototype.promptAllUnsaved=function(a){this.promptAllUnsavedFromIndex_(0,a)};
Tabs.prototype.promptAllUnsavedFromIndex_=function(a,b){if(a>=this.tabs_.length)b();else{var c=this.tabs_[a];c.isSaved()?this.promptAllUnsavedFromIndex_(a+1,b):(this.showTab(this.tabs_[a].getId()),this.promptSave_(c,function(d){"yes"===d?this.save(c,this.promptAllUnsavedFromIndex_.bind(this,a+1,b)):"no"===d&&this.promptAllUnsavedFromIndex_(a+1,b)}.bind(this)))}};
Tabs.prototype.promptSave_=function(a,b){this.dialogController_.setText(chrome.i18n.getMessage("saveFilePromptLine1",a.getName()),chrome.i18n.getMessage("saveFilePromptLine2"));this.dialogController_.resetButtons();this.dialogController_.addButton("yes",chrome.i18n.getMessage("yesDialogButton"));this.dialogController_.addButton("no",chrome.i18n.getMessage("noDialogButton"));this.dialogController_.addButton("cancel",chrome.i18n.getMessage("cancelDialogButton"));this.dialogController_.show(b)};
Tabs.prototype.save=function(a,b){var c=a||this.currentTab_;c&&c===this.currentTab_&&this.updateCurrentTabState_();c.getEntry()?c.save(b):this.saveAs(c,b)};Tabs.prototype.saveAs=function(a,b){var c=a||this.currentTab_;c&&c===this.currentTab_&&this.updateCurrentTabState_();var d=c.getEntry()&&c.getEntry().name||util.sanitizeFileName(c.session_.doc.line(1).text)||c.getName();util.getExtension(d)||(d+=".txt");this.chooseEntry({type:"saveFile",suggestedName:d},function(e){this.saveEntry_(c,e,b);b&&b()}.bind(this))};
Tabs.prototype.getFilesToRetain=function(){var a=[];for(i=0;i<this.tabs_.length;i++)this.tabs_[i].getEntry()&&a.push(this.tabs_[i].getEntry());return a};Tabs.prototype.openFileEntry=function(a){chrome.fileSystem.getDisplayPath(a,function(b){for(var c=0;c<this.tabs_.length;c++)if(this.tabs_[c].getPath()===b){this.showTab(this.tabs_[c].getId());return}a.file(this.readFileToNewTab_.bind(this,a))}.bind(this))};Tabs.prototype.modeAutoSet=function(a){a===this.currentTab_&&(a=a.getExtension())&&this.editor_.updateMode(a)};
Tabs.prototype.readFileToNewTab_=function(a,b){$.event.trigger("loadingfile");var c=this,d=new FileReader;d.onerror=util.handleFSError;d.onloadend=function(e){c.newTab(this.result,a);2===c.tabs_.length&&!c.tabs_[0].getEntry()&&c.tabs_[0].isSaved()&&c.close(c.tabs_[0].getId())};d.readAsText(b)};Tabs.prototype.saveEntry_=function(a,b,c){b&&(a.setEntry(b),this.save(a,c))};Tabs.prototype.onDocChanged_=function(){this.currentTab_.changed()};Tabs.prototype.hasOpenTab=function(){return!!this.tabs_.length};var util={fsErrorStr:function(a){switch(a.code){case FileError.QUOTA_EXCEEDED_ERR:return"Quota exceeded";case FileError.NOT_FOUND_ERR:return"File not found";case FileError.SECURITY_ERR:return"Security error";case FileError.INVALID_MODIFICATION_ERR:return"Invalid modification";case FileError.INVALID_STATE_ERR:return"Invalid state";default:return"Unknown Error"}},handleFSError:function(a){$.event.trigger("filesystemerror");console.warn("FS Error:",util.fsErrorStr(a),a)},writeFile:function(a,b,c,d){var e=
new Blob([b],{type:"text/plain"});a.createWriter(function(f){f.onerror=d?d:util.handleFSError;f.onwrite=util.writeToWriter_.bind(null,f,e,c);f.truncate(e.size)})},writeToWriter_:function(a,b,c){a.onwrite=c;a.write(b)},sanitizeFileName:function(a){return a.replace(/[^a-z0-9\-]/gi," ").substr(0,50).trim()},getExtension:function(a){return(a=/\.([^.\\\/]+)$/.exec(a))?a[1]:null},guessLineEndings:function(a){if(!a)return"\n";var b=a.indexOf("\n");return 0<b&&"\r"===a[b-1]?"\r\n":"\n"}};function DialogController(a,b){this.container_=a;this.editor_=b;this.disabledElements_=[]}DialogController.prototype.show=function(a){this.container_.hasClass("open")?(console.error("Trying to open dialog when it is already visible."),console.error(Error())):(this.callback_=a,this.container_.addClass("open"),this.disableEverything_(),$(document).bind("keydown.dialog",this.onKeydown_.bind(this)),this.container_.find(".dialog-button").first().focus())};
DialogController.prototype.disableEverything_=function(){this.editor_.disable();for(var a=document.querySelectorAll("input, textarea, .mdc-icon-button"),b=0;b<a.length;b++)this.disabledElements_.push({element:a[b],index:a[b].tabIndex}),a[b].tabIndex=-1};DialogController.prototype.reenableEverything_=function(){for(var a=0;a<this.disabledElements_.length;a++)this.disabledElements_[a].element.tabIndex=this.disabledElements_[a].index;this.editor_.enable()};DialogController.prototype.resetButtons=function(){this.container_.find(".dialog-button").remove()};
DialogController.prototype.addButton=function(a,b){var c=$('<button class="dialog-button"></button>');c.attr("id",a);c.text(b);c.click(this.onClick_.bind(this,a));c.keydown(this.onKeydown_.bind(this));this.container_.find(".dialog-buttons").append(c)};
DialogController.prototype.setText=function(a){var b=this.container_[0].querySelector(".dialog-text");b.innerHTML=null;b.appendChild(document.createTextNode(arguments[0]||""));for(var c=1;c<arguments.length;c++)b.appendChild(document.createElement("br")),b.appendChild(document.createTextNode(arguments[c]))};DialogController.prototype.onClick_=function(a){$(document).unbind("keydown.dialog");this.container_.removeClass("open");this.reenableEverything_();this.callback_&&this.callback_(a)};
DialogController.prototype.next_=function(a){var b=$(".dialog-button");a=$.inArray(document.activeElement,b)+a;0>a&&(a+=b.length);a>=b.length&&(a-=b.length);$(b[a]).focus()};DialogController.prototype.onKeydown_=function(a){a.stopPropagation();switch(a.keyCode){case 27:return this.onClick_("cancel"),!1;case 37:return this.next_(-1),!1;case 39:return this.next_(1),!1}};function HotkeysController(a,b,c,d,e){this.windowController_=a;this.tabs_=b;this.editor_=c;this.settings_=d;this.settingsController_=e;this.ZOOM_IN_FACTOR=1.125;this.ZOOM_OUT_FACTOR=8/9;$(document).keydown(this.onKeydown_.bind(this))}
HotkeysController.prototype.onKeydown_=function(a){if(a.ctrlKey||a.metaKey)switch(a.key){case "Tab":return a.shiftKey?this.tabs_.previousTab():this.tabs_.nextTab(),!1;case "e":case "E":return this.windowController_.openSidebar(),this.settingsController_.closeSettings(),document.querySelector(".sidebar-button").focus(),!1;case "f":case "F":return document.getElementById("search-input").focus(),!1;case "n":case "N":return a.shiftKey?this.tabs_.newWindow():this.tabs_.newTab(),!1;case "o":case "O":return this.tabs_.openFiles(),
!1;case "p":case "P":return window.print(),!1;case "s":case "S":return a.shiftKey?this.tabs_.saveAs():this.tabs_.save(),!1;case "w":case "W":return a.shiftKey?this.windowController_.close():this.tabs_.closeCurrent(),!1;case "0":case ")":return this.settings_.reset("fontsize"),!1;case "+":case "=":return a=this.settings_.get("fontsize"),this.settings_.set("fontsize",a*this.ZOOM_IN_FACTOR),!1;case "-":case "_":return a=this.settings_.get("fontsize"),this.settings_.set("fontsize",a*this.ZOOM_OUT_FACTOR),
!1}else if(a.altKey&&" "===a.key)return $("#toggle-sidebar").click(),!1};function MenuController(a){this.tabs_=a;this.dragItem_=null;$("#file-menu-new").click(this.newTab_.bind(this));$("#file-menu-open").click(this.open_.bind(this));$("#file-menu-save").click(this.save_.bind(this));$("#file-menu-saveas").click(this.saveas_.bind(this));$("#open-shortcuts").click(this.openShortcuts_.bind(this));$(document).bind("newtab",this.addNewTab_.bind(this));$(document).bind("switchtab",this.onSwitchTab.bind(this));$(document).bind("tabchange",this.onTabChange.bind(this));$(document).bind("tabclosed",
this.onTabClosed.bind(this));$(document).bind("tabpathchange",this.onTabPathChange.bind(this));$(document).bind("tabrenamed",this.onTabRenamed.bind(this));$(document).bind("tabsave",this.onTabSave.bind(this))}
MenuController.prototype.addNewTab_=function(a,b){var c=this,d=b.getId(),e=document.createElement("li");e.setAttribute("draggable","true");var f=document.createElement("button");f.id="tab"+d;f.textContent=b.getName();f.className="filename sidebar-button";e.appendChild(f);var h=document.createElement("button");h.textContent="close";h.setAttribute("title",chrome.i18n.getMessage("closeFileButton"));h.classList.add("close","mdc-icon-button","material-icons");mdc.ripple.MDCRipple.attachTo(h).unbounded=
!0;e.appendChild(h);document.getElementById("tabs-list").appendChild(e);e.addEventListener("dragstart",function(){c.onDragStart_($(e))});e.addEventListener("dragover",function(g){c.onDragOver_($(e),g)});e.addEventListener("dragend",function(g){c.onDragEnd_($(e),g)});e.addEventListener("drop",function(g){c.onDrop_(g)});f.addEventListener("click",function(){c.tabButtonClicked_(d)});h.addEventListener("click",function(g){c.closeTab_(g,d)})};
MenuController.prototype.onDragStart_=function(a){this.dragItem_=a};MenuController.prototype.onDragEnd_=function(a,b){this.dragItem_=null;b.preventDefault();b.stopPropagation()};MenuController.prototype.onDrop_=function(a){a.stopPropagation()};
MenuController.prototype.onDragOver_=function(a,b){b.preventDefault();this.dragItem_&&a.find(".filename").attr("id")!==this.dragItem_.find(".filename").attr("id")&&(this.dragItem_.index()<a.index()?a.after(this.dragItem_):a.before(this.dragItem_),this.tabs_.reorder(this.dragItem_.index(),a.index()))};MenuController.prototype.onTabRenamed=function(a,b){$("#tab"+b.getId()+".filename").text(b.getName());this.tabs_.modeAutoSet(b)};
MenuController.prototype.onTabPathChange=function(a,b){$("#tab"+b.getId()+".filename").attr("title",b.getPath())};MenuController.prototype.onTabChange=function(a,b){$("#tab"+b.getId()).addClass("unsaved")};MenuController.prototype.onTabClosed=function(a,b){$("#tab"+b.getId()).parent().remove()};MenuController.prototype.onTabSave=function(a,b){$("#tab"+b.getId()).removeClass("unsaved")};MenuController.prototype.onSwitchTab=function(a,b){$("#tabs-list .active").removeClass("active");$("#tab"+b.getId()).parent().addClass("active")};
MenuController.prototype.newTab_=function(){this.tabs_.newTab();return!1};MenuController.prototype.open_=function(){this.tabs_.openFiles();return!1};MenuController.prototype.save_=function(){this.tabs_.save();return!1};MenuController.prototype.saveas_=function(){this.tabs_.saveAs();return!1};MenuController.prototype.openShortcuts_=function(){window.open("https://support.google.com/chromebook/answer/183101#textapp","_blank");return!1};
MenuController.prototype.tabButtonClicked_=function(a){this.tabs_.showTab(a);return!1};MenuController.prototype.closeTab_=function(a,b){this.tabs_.close(b);a.stopPropagation()};function SearchController(a){var b=this;this.search_=a;this.activating_=!1;document.getElementById("search-input").addEventListener("focus",function(){b.activateSearch_()});$("#search-input").bind("input",this.onChange_.bind(this));$("#search-input").keydown(this.onKeydown_.bind(this));document.getElementById("search-counting").addEventListener("mousedown",function(c){c.preventDefault()});$("#search-next-button").click(this.onFindNext_.bind(this));$("#search-previous-button").click(this.onFindPrevious_.bind(this));
$(".search-container").focusout(this.deactivateSearch_.bind(this))}SearchController.prototype.updateSearchCount_=function(){if(0===$("#search-input").val().length)return $("#search-counting").text(""),0;var a=this.search_.getResultsCount(),b=this.search_.getCurrentIndex();$("#search-counting").text(chrome.i18n.getMessage("searchCounting",[b,a]));0===a?$("#search-counting").addClass("nomatches"):$("#search-counting").removeClass("nomatches");return a};
SearchController.prototype.findNext_=function(a){this.search_.getQuery()&&(this.search_.findNext(a),this.updateSearchCount_(a))};SearchController.prototype.activateSearch_=function(){this.activating_||(this.activating_=!0,this.search_.activate(),document.getElementById("search-input").select(),$("header").addClass("search-active"),this.activating_=!1)};
SearchController.prototype.deactivateSearch_=function(a){this.activating_||a.relatedTarget&&a.relatedTarget.closest(".search-container")||($("#search-input").val(""),$("#search-counting").text(""),$("header").removeClass("search-active"),$(".search-navigation-button").removeClass("has-results"),this.search_.deactivate())};
SearchController.prototype.onChange_=function(){var a=$("#search-input").val();a!==this.search_.getQuery()&&(this.search_.find(a),0<this.updateSearchCount_()?$(".search-navigation-button").addClass("has-results"):$(".search-navigation-button").removeClass("has-results"))};SearchController.prototype.onKeydown_=function(a){switch(a.key){case "Enter":a.stopPropagation();this.findNext_(a.shiftKey);break;case "Escape":a.stopPropagation(),this.search_.unfocus()}};
SearchController.prototype.onFindNext_=function(){this.findNext_()};SearchController.prototype.onFindPrevious_=function(){this.findNext_(!0)};function SettingsController(a){this.settings_=a;this.settings_.isReady()?this.showAll_():$(document).bind("settingsready",this.showAll_.bind(this));$(document).bind("settingschange",this.onSettingChange_.bind(this));this.addInputListeners_();$("#open-settings").click(this.openSettings_.bind(this));$("#close-settings").click(this.closeSettings.bind(this))}
SettingsController.prototype.addInputListeners_=function(){var a=this,b={},c;for(c in Settings.SETTINGS)switch(b={key$jscomp$49:b.key$jscomp$49},b.key$jscomp$49=c,Settings.SETTINGS[b.key$jscomp$49].widget){case "checkbox":case "number":$("#setting-"+b.key$jscomp$49).change(this.saveSetting_.bind(this,b.key$jscomp$49));break;case "radio":for(var d=$jscomp.makeIterator(document.querySelectorAll("input[name=setting-"+b.key$jscomp$49+"]")),e=d.next();!e.done;e=d.next())e.value.addEventListener("input",
function(f){return function(){return a.saveSetting_(f.key$jscomp$49)}}(b))}};SettingsController.prototype.openSettings_=function(){$("#sidebar").addClass("open-settings");$("#settings-list input:first").focus()};SettingsController.prototype.closeSettings=function(){$("#sidebar").removeClass("open-settings");$("#open-settings").focus()};SettingsController.prototype.showAll_=function(){var a=this.settings_.getAll(),b;for(b in a)this.show_(b,a[b])};
SettingsController.prototype.show_=function(a,b){switch(Settings.SETTINGS[a].widget){case "checkbox":this.setSwitch_(a,b);break;case "number":$("#setting-"+a).val(parseInt(b));break;case "radio":document.getElementById("setting-"+a+"-"+b).setAttribute("checked","")}};SettingsController.prototype.setSwitch_=function(a,b){document.getElementById("setting-"+a).toggleAttribute("checked",b);document.getElementById("setting-"+a+"-switch").classList.toggle("mdc-switch--checked",b)};
SettingsController.prototype.onSettingChange_=function(a,b,c){this.show_(b,c)};SettingsController.prototype.saveSetting_=function(a){switch(Settings.SETTINGS[a].widget){case "checkbox":var b=$("#setting-"+a).prop("checked");break;case "number":b=parseInt($("#setting-"+a).val());break;case "radio":b=document.querySelector("input[name=setting-"+a+"]:checked").getAttribute("value")}this.settings_.set(a,b)};function WindowController(a,b,c){var d=this;this.editor_=a;this.settings_=b;this.tabs_=c;document.getElementById("window-close").addEventListener("click",function(){d.close()});$("#window-minimize").click(this.minimize_.bind(this));$("#window-maximize").click(this.maximize_.bind(this));$("#toggle-sidebar").click(this.toggleSidebar_.bind(this));$("#sidebar").on("transitionend",this.updateSidebarVisibility_.bind(this));$("#sidebar-resizer").mousedown(this.resizeStart_.bind(this));$(window).bind("error",
this.onError_.bind(this));$(document).bind("filesystemerror",this.onFileSystemError.bind(this));$(document).bind("loadingfile",this.onLoadingFile.bind(this));$(document).bind("switchtab",this.onChangeTab_.bind(this));$(document).bind("tabchange",this.onTabChange_.bind(this));$(document).bind("tabpathchange",this.onTabPathChange.bind(this));$(document).bind("tabrenamed",this.onChangeTab_.bind(this));$(document).bind("tabsave",this.onTabChange_.bind(this));this.initUI_()}
WindowController.prototype.initUI_=function(){for(var a=$jscomp.makeIterator(document.querySelectorAll(".mdc-icon-button")),b=a.next(),c={};!b.done;c={ripple:c.ripple},b=a.next())b=b.value,c.ripple=mdc.ripple.MDCRipple.attachTo(b),c.ripple.unbounded=!0,(new ResizeObserver(function(d){return function(){d.ripple.layout()}}(c))).observe(b);a=$jscomp.makeIterator(document.querySelectorAll(".mdc-switch"));for(b=a.next();!b.done;b=a.next())new mdc.switchControl.MDCSwitch(b.value);a=$jscomp.makeIterator(document.querySelectorAll(".mdc-radio"));
for(b=a.next();!b.done;b=a.next())b=b.value,(new mdc.formField.MDCFormField(b.parentElement)).input=new mdc.radio.MDCRadio(b);this.settings_.isReady()?this.initSidebar_():$(document).bind("settingsready",this.initSidebar_.bind(this))};
WindowController.prototype.initSidebar_=function(){this.settings_.get("sidebaropen")?($("#sidebar").css("width",this.settings_.get("sidebarwidth")+"px"),$("#sidebar").css("border-right-width","2px"),$("#toggle-sidebar").attr("title",chrome.i18n.getMessage("closeSidebarButton"))):($("#sidebar").css("width","0"),$("#sidebar").css("border-right-width","0"),$("#toggle-sidebar").attr("title",chrome.i18n.getMessage("openSidebarButton")));this.updateSidebarVisibility_()};
WindowController.prototype.windowControlsVisible=function(a){a?$("header").removeClass("hide-controls"):$("header").addClass("hide-controls")};WindowController.prototype.setTheme=function(a){$("body").attr("theme",a)};WindowController.prototype.close=function(){this.tabs_.promptAllUnsaved(window.close)};WindowController.prototype.focus_=function(){window.chrome.app.window.current().focus()};WindowController.prototype.minimize_=function(){window.chrome.app.window.current().minimize()};
WindowController.prototype.maximize_=function(){window.chrome.app.window.current().isMaximized()?(window.chrome.app.window.current().restore(),$("#window-maximize").attr("title",chrome.i18n.getMessage("maximizeButton"))):(window.chrome.app.window.current().maximize(),$("#window-maximize").attr("title",chrome.i18n.getMessage("restoreButton")))};WindowController.prototype.setAlwaysOnTop=function(a){window.chrome.app.window.current().setAlwaysOnTop(a)};
WindowController.prototype.openSidebar=function(){this.settings_.get("sidebaropen")||(this.settings_.set("sidebaropen",!0),$("#sidebar").css("width",this.settings_.get("sidebarwidth")+"px"),$("#sidebar").css("border-right-width","2px"),$("#sidebar").css("visibility","visible"),$("#toggle-sidebar").attr("title",chrome.i18n.getMessage("closeSidebarButton")))};
WindowController.prototype.toggleSidebar_=function(){this.settings_.get("sidebaropen")?(this.settings_.set("sidebaropen",!1),$("#sidebar").css("width","0"),$("#sidebar").css("border-right-width","0"),$("#toggle-sidebar").attr("title",chrome.i18n.getMessage("openSidebarButton"))):this.openSidebar()};WindowController.prototype.onLoadingFile=function(a){$("#title-filename").text(chrome.i18n.getMessage("loadingTitle"))};WindowController.prototype.onFileSystemError=function(a){$("#title-filename").text(chrome.i18n.getMessage("errorTitle"))};
WindowController.prototype.onChangeTab_=function(a,b){$("#title-filename").text(b.getName());this.onTabChange_()};WindowController.prototype.onTabPathChange=function(a,b){$("#title-filename").attr("title",b.getPath())};WindowController.prototype.onTabChange_=function(a,b){this.tabs_.getCurrentTab().isSaved()?$("#title-filename").removeClass("unsaved"):$("#title-filename").addClass("unsaved")};
WindowController.prototype.resizeStart_=function(a){this.resizeMouseStartX_=a.clientX;this.resizeStartWidth_=parseInt($("#sidebar").css("width"),10);$(document).on("mousemove.sidebar",this.resizeOnMouseMove_.bind(this));$(document).on("mouseup.sidebar",this.resizeFinish_.bind(this));$(document).css("cursor","e-resize !important");$("#sidebar").css("-webkit-transition","none")};
WindowController.prototype.resizeOnMouseMove_=function(a){a=this.resizeStartWidth_+(a.clientX-this.resizeMouseStartX_);20>a&&(a=20);$("#sidebar").css("width",a+"px");return a};WindowController.prototype.resizeFinish_=function(a){a=this.resizeOnMouseMove_(a);this.settings_.set("sidebarwidth",a);$(document).off("mousemove.sidebar");$(document).off("mouseup.sidebar");$(document).css("cursor","default");$("#sidebar").css("-webkit-transition","width 0.2s ease-in-out")};
WindowController.prototype.updateSidebarVisibility_=function(){var a=$("#sidebar");0===a.width()?a.css("visibility","hidden"):a.css("visibility","visible")};WindowController.prototype.onError_=function(a){};